/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.common.pojo.shop.goods.dao;


import lombok.Data;

import java.math.BigDecimal;
import java.sql.Timestamp;

/**
 * 商品sku表
 * @author 李晓冰
 * @date 2020年07月02日
 */
@Data
public class GoodsSpecProductDo {
    private Integer prdId;
    private Integer goodsId;
    private String prdSn;
    private BigDecimal prdPrice;
    private BigDecimal prdMarketPrice;
    private BigDecimal prdCostPrice;
    private Integer prdNumber;
    private String prdCodes;
    private String prdSpecs;
    private String prdDesc;
    private String prdImg;
    private BigDecimal prdWeight;
    private Byte delFlag;
    private Timestamp createTime;

    @Override
    public String toString() {
        return "GoodsSpecProduct{" +
            "prdId=" + prdId +
            ", goodsId=" + goodsId +
            ", prdSn='" + prdSn + '\'' +
            ", prdPrice=" + prdPrice +
            ", prdMarketPrice=" + prdMarketPrice +
            ", prdCostPrice=" + prdCostPrice +
            ", prdNumber=" + prdNumber +
            ", prdCodes='" + prdCodes + '\'' +
            ", prdSpecs='" + prdSpecs + '\'' +
            ", prdDesc='" + prdDesc + '\'' +
            ", prdImg='" + prdImg + '\'' +
            ", prdWeight=" + prdWeight +
            ", delFlag=" + delFlag +
            ", createTime=" + createTime +
            '}';
    }
}
