package com.vpu.mp.service.shop.goods.es.goods;

import static com.vpu.mp.service.pojo.shop.goods.es.EsSearchName.*;

public class EsSearchFieldsConstant {
    public static final String[] DEFAULT_STR = {GOODS_ID,SHOP_ID,IS_ON_SALE,GOODS_NUMBER};

    public static final String[] GOODS_SEARCH_STR = {
        V1,
        V2,
        V3,
        V4,
        V5,
        V6,
        V7,
        V8,
        V9,
        GOODS_ID,
        SHOP_ID,
        IS_ON_SALE,
        GOODS_NUMBER,
        GOODS_NAME,
        FIRST_CAT_ID,
        FIRST_SORT_ID,
        GOODS_IMG,
        GOODS_SN,
        SHOP_PRICE,
        SOURCE,
        GOODS_TYPE,
        CAT_ID,
        CAT_NAME,
        SORT_ID,
        SORT_NAME,
        BRAND_NAME,
        BRAND_ID,
        GOODS_SALE_NUM,
        GOODS_LABEL,
        PRD_SNS,
        MAX_SPEC_PRD_PRICE,
        MIN_SPEC_PRD_PRICE,
        FREIGHT_TEMPLATE_ID,
        PRD_JSON,
        BASE_SALE,
        DEFAULT_PRD,
        CAN_REBATE,
        LIMIT_BUY_NUM,
        LIMIT_MAX_NUM,
        MARKET_PRICE,
        GOODS_PAGE_ID,
        GOODS_WEIGHT,
        GOODS_DESC,
        ROOM_ID,
        SECONDARY_GOODS_IMAGES,
        PRDS,
        VIDEO_INFO_JSON,
        PRD.PRD_ID,
        PRD.PRD_SN,
        PRD.PRD_REAL_PRICE,
        PRD.PRD_IMG,
        PRD.PRD_DESC
    };
}
