/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FriendPromoteDetail implements Serializable {

    private static final long serialVersionUID = 130904187;

    private UInteger  id;
    private Integer   launchId;
    private Integer   userId;
    private Integer   promoteId;
    private Integer   promoteValue;
    private Timestamp promoteTime;
    private Timestamp updateTime;

    public FriendPromoteDetail() {}

    public FriendPromoteDetail(FriendPromoteDetail value) {
        this.id = value.id;
        this.launchId = value.launchId;
        this.userId = value.userId;
        this.promoteId = value.promoteId;
        this.promoteValue = value.promoteValue;
        this.promoteTime = value.promoteTime;
        this.updateTime = value.updateTime;
    }

    public FriendPromoteDetail(
        UInteger  id,
        Integer   launchId,
        Integer   userId,
        Integer   promoteId,
        Integer   promoteValue,
        Timestamp promoteTime,
        Timestamp updateTime
    ) {
        this.id = id;
        this.launchId = launchId;
        this.userId = userId;
        this.promoteId = promoteId;
        this.promoteValue = promoteValue;
        this.promoteTime = promoteTime;
        this.updateTime = updateTime;
    }

    public UInteger getId() {
        return this.id;
    }

    public void setId(UInteger id) {
        this.id = id;
    }

    public Integer getLaunchId() {
        return this.launchId;
    }

    public void setLaunchId(Integer launchId) {
        this.launchId = launchId;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    public Integer getPromoteId() {
        return this.promoteId;
    }

    public void setPromoteId(Integer promoteId) {
        this.promoteId = promoteId;
    }

    public Integer getPromoteValue() {
        return this.promoteValue;
    }

    public void setPromoteValue(Integer promoteValue) {
        this.promoteValue = promoteValue;
    }

    public Timestamp getPromoteTime() {
        return this.promoteTime;
    }

    public void setPromoteTime(Timestamp promoteTime) {
        this.promoteTime = promoteTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("FriendPromoteDetail (");

        sb.append(id);
        sb.append(", ").append(launchId);
        sb.append(", ").append(userId);
        sb.append(", ").append(promoteId);
        sb.append(", ").append(promoteValue);
        sb.append(", ").append(promoteTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
