/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables.records;


import com.vpu.mp.db.shop.tables.InquiryOrderRebate;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 医师问诊订单返利表
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InquiryOrderRebateRecord extends UpdatableRecordImpl<InquiryOrderRebateRecord> implements Record10<Integer, String, Integer, BigDecimal, BigDecimal, Byte, Byte, Timestamp, Timestamp, Timestamp> {

    private static final long serialVersionUID = 2133634196;

    /**
     * Setter for <code>mini_shop_471752.b2c_inquiry_order_rebate.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_inquiry_order_rebate.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_inquiry_order_rebate.order_sn</code>. 订单号
     */
    public void setOrderSn(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_inquiry_order_rebate.order_sn</code>. 订单号
     */
    public String getOrderSn() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_inquiry_order_rebate.doctor_id</code>. 医师id
     */
    public void setDoctorId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_inquiry_order_rebate.doctor_id</code>. 医师id
     */
    public Integer getDoctorId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_inquiry_order_rebate.total_money</code>. 问诊金额
     */
    public void setTotalMoney(BigDecimal value) {
        set(3, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_inquiry_order_rebate.total_money</code>. 问诊金额
     */
    public BigDecimal getTotalMoney() {
        return (BigDecimal) get(3);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_inquiry_order_rebate.total_rebate_money</code>. 返利金额
     */
    public void setTotalRebateMoney(BigDecimal value) {
        set(4, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_inquiry_order_rebate.total_rebate_money</code>. 返利金额
     */
    public BigDecimal getTotalRebateMoney() {
        return (BigDecimal) get(4);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_inquiry_order_rebate.status</code>. 状态  0待返利 1已返利
     */
    public void setStatus(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_inquiry_order_rebate.status</code>. 状态  0待返利 1已返利
     */
    public Byte getStatus() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_inquiry_order_rebate.is_delete</code>. 删除
     */
    public void setIsDelete(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_inquiry_order_rebate.is_delete</code>. 删除
     */
    public Byte getIsDelete() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_inquiry_order_rebate.rebate_time</code>. 返利日期
     */
    public void setRebateTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_inquiry_order_rebate.rebate_time</code>. 返利日期
     */
    public Timestamp getRebateTime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_inquiry_order_rebate.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_inquiry_order_rebate.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_inquiry_order_rebate.update_time</code>. 最后修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_inquiry_order_rebate.update_time</code>. 最后修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, Integer, BigDecimal, BigDecimal, Byte, Byte, Timestamp, Timestamp, Timestamp> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<Integer, String, Integer, BigDecimal, BigDecimal, Byte, Byte, Timestamp, Timestamp, Timestamp> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return InquiryOrderRebate.INQUIRY_ORDER_REBATE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return InquiryOrderRebate.INQUIRY_ORDER_REBATE.ORDER_SN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return InquiryOrderRebate.INQUIRY_ORDER_REBATE.DOCTOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field4() {
        return InquiryOrderRebate.INQUIRY_ORDER_REBATE.TOTAL_MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field5() {
        return InquiryOrderRebate.INQUIRY_ORDER_REBATE.TOTAL_REBATE_MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return InquiryOrderRebate.INQUIRY_ORDER_REBATE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return InquiryOrderRebate.INQUIRY_ORDER_REBATE.IS_DELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return InquiryOrderRebate.INQUIRY_ORDER_REBATE.REBATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return InquiryOrderRebate.INQUIRY_ORDER_REBATE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return InquiryOrderRebate.INQUIRY_ORDER_REBATE.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getOrderSn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getDoctorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component4() {
        return getTotalMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component5() {
        return getTotalRebateMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getRebateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getOrderSn();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDoctorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value4() {
        return getTotalMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value5() {
        return getTotalRebateMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getRebateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryOrderRebateRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryOrderRebateRecord value2(String value) {
        setOrderSn(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryOrderRebateRecord value3(Integer value) {
        setDoctorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryOrderRebateRecord value4(BigDecimal value) {
        setTotalMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryOrderRebateRecord value5(BigDecimal value) {
        setTotalRebateMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryOrderRebateRecord value6(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryOrderRebateRecord value7(Byte value) {
        setIsDelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryOrderRebateRecord value8(Timestamp value) {
        setRebateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryOrderRebateRecord value9(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryOrderRebateRecord value10(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InquiryOrderRebateRecord values(Integer value1, String value2, Integer value3, BigDecimal value4, BigDecimal value5, Byte value6, Byte value7, Timestamp value8, Timestamp value9, Timestamp value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InquiryOrderRebateRecord
     */
    public InquiryOrderRebateRecord() {
        super(InquiryOrderRebate.INQUIRY_ORDER_REBATE);
    }

    /**
     * Create a detached, initialised InquiryOrderRebateRecord
     */
    public InquiryOrderRebateRecord(Integer id, String orderSn, Integer doctorId, BigDecimal totalMoney, BigDecimal totalRebateMoney, Byte status, Byte isDelete, Timestamp rebateTime, Timestamp createTime, Timestamp updateTime) {
        super(InquiryOrderRebate.INQUIRY_ORDER_REBATE);

        set(0, id);
        set(1, orderSn);
        set(2, doctorId);
        set(3, totalMoney);
        set(4, totalRebateMoney);
        set(5, status);
        set(6, isDelete);
        set(7, rebateTime);
        set(8, createTime);
        set(9, updateTime);
    }
}
