/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables.records;



import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import com.vpu.mp.db.shop.tables.Patient;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 患者信息
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PatientRecord extends UpdatableRecordImpl<PatientRecord> implements Record16<Integer, String, String, String, String, Byte, String, Byte, Byte, Date, String, String, String, Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1057099627;

    /**
     * Setter for <code>jmini_shop_224462.b2c_patient.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jmini_shop_224462.b2c_patient.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jmini_shop_224462.b2c_patient.name</code>. 患者名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jmini_shop_224462.b2c_patient.name</code>. 患者名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jmini_shop_224462.b2c_patient.mobile</code>. 手机号码
     */
    public void setMobile(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jmini_shop_224462.b2c_patient.mobile</code>. 手机号码
     */
    public String getMobile() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jmini_shop_224462.b2c_patient.patient_code</code>. 医院内部患者唯一编码
     */
    public void setPatientCode(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>jmini_shop_224462.b2c_patient.patient_code</code>. 医院内部患者唯一编码
     */
    public String getPatientCode() {
        return (String) get(3);
    }

    /**
     * Setter for <code>jmini_shop_224462.b2c_patient.identity_no</code>. 证件号码
     */
    public void setIdentityNo(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>jmini_shop_224462.b2c_patient.identity_no</code>. 证件号码
     */
    public String getIdentityNo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>jmini_shop_224462.b2c_patient.identity_type</code>. 证件类型: 1：身份证 2：军人证 3：护照 4：社保卡
     */
    public void setIdentityType(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>jmini_shop_224462.b2c_patient.identity_type</code>. 证件类型: 1：身份证 2：军人证 3：护照 4：社保卡
     */
    public Byte getIdentityType() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>jmini_shop_224462.b2c_patient.treatment_no</code>. 就诊卡号
     */
    public void setTreatmentNo(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>jmini_shop_224462.b2c_patient.treatment_no</code>. 就诊卡号
     */
    public String getTreatmentNo() {
        return (String) get(6);
    }

    /**
     * Setter for <code>jmini_shop_224462.b2c_patient.area_type</code>. 患者类型 0本地 1外地 2境外 9其它
     */
    public void setAreaType(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>jmini_shop_224462.b2c_patient.area_type</code>. 患者类型 0本地 1外地 2境外 9其它
     */
    public Byte getAreaType() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>jmini_shop_224462.b2c_patient.sex</code>. 性别 0：未知 1：男 2：女
     */
    public void setSex(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>jmini_shop_224462.b2c_patient.sex</code>. 性别 0：未知 1：男 2：女
     */
    public Byte getSex() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>jmini_shop_224462.b2c_patient.birthday</code>. 出生年月
     */
    public void setBirthday(Date value) {
        set(9, value);
    }

    /**
     * Getter for <code>jmini_shop_224462.b2c_patient.birthday</code>. 出生年月
     */
    public Date getBirthday() {
        return (Date) get(9);
    }

    /**
     * Setter for <code>jmini_shop_224462.b2c_patient.disease_history</code>. 疾病史
     */
    public void setDiseaseHistory(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>jmini_shop_224462.b2c_patient.disease_history</code>. 疾病史
     */
    public String getDiseaseHistory() {
        return (String) get(10);
    }

    /**
     * Setter for <code>jmini_shop_224462.b2c_patient.allergy_history</code>. 过敏史
     */
    public void setAllergyHistory(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>jmini_shop_224462.b2c_patient.allergy_history</code>. 过敏史
     */
    public String getAllergyHistory() {
        return (String) get(11);
    }

    /**
     * Setter for <code>jmini_shop_224462.b2c_patient.memo</code>. 备注
     */
    public void setMemo(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>jmini_shop_224462.b2c_patient.memo</code>. 备注
     */
    public String getMemo() {
        return (String) get(12);
    }

    /**
     * Setter for <code>jmini_shop_224462.b2c_patient.is_delete</code>.
     */
    public void setIsDelete(Byte value) {
        set(13, value);
    }

    /**
     * Getter for <code>jmini_shop_224462.b2c_patient.is_delete</code>.
     */
    public Byte getIsDelete() {
        return (Byte) get(13);
    }

    /**
     * Setter for <code>jmini_shop_224462.b2c_patient.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(14, value);
    }

    /**
     * Getter for <code>jmini_shop_224462.b2c_patient.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(14);
    }

    /**
     * Setter for <code>jmini_shop_224462.b2c_patient.update_time</code>. 最后修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>jmini_shop_224462.b2c_patient.update_time</code>. 最后修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, String, String, String, String, Byte, String, Byte, Byte, Date, String, String, String, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, String, String, String, String, Byte, String, Byte, Byte, Date, String, String, String, Byte, Timestamp, Timestamp> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Patient.PATIENT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Patient.PATIENT.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Patient.PATIENT.MOBILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Patient.PATIENT.PATIENT_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Patient.PATIENT.IDENTITY_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return Patient.PATIENT.IDENTITY_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Patient.PATIENT.TREATMENT_NO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return Patient.PATIENT.AREA_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return Patient.PATIENT.SEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field10() {
        return Patient.PATIENT.BIRTHDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Patient.PATIENT.DISEASE_HISTORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Patient.PATIENT.ALLERGY_HISTORY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Patient.PATIENT.MEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field14() {
        return Patient.PATIENT.IS_DELETE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field15() {
        return Patient.PATIENT.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field16() {
        return Patient.PATIENT.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getPatientCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getIdentityNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getIdentityType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getTreatmentNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component8() {
        return getAreaType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component9() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component10() {
        return getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getDiseaseHistory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getAllergyHistory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component14() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component15() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component16() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getPatientCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getIdentityNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getIdentityType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getTreatmentNo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getAreaType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value10() {
        return getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getDiseaseHistory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getAllergyHistory();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value14() {
        return getIsDelete();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value15() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value16() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatientRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatientRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatientRecord value3(String value) {
        setMobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatientRecord value4(String value) {
        setPatientCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatientRecord value5(String value) {
        setIdentityNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatientRecord value6(Byte value) {
        setIdentityType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatientRecord value7(String value) {
        setTreatmentNo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatientRecord value8(Byte value) {
        setAreaType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatientRecord value9(Byte value) {
        setSex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatientRecord value10(Date value) {
        setBirthday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatientRecord value11(String value) {
        setDiseaseHistory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatientRecord value12(String value) {
        setAllergyHistory(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatientRecord value13(String value) {
        setMemo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatientRecord value14(Byte value) {
        setIsDelete(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatientRecord value15(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatientRecord value16(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PatientRecord values(Integer value1, String value2, String value3, String value4, String value5, Byte value6, String value7, Byte value8, Byte value9, Date value10, String value11, String value12, String value13, Byte value14, Timestamp value15, Timestamp value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PatientRecord
     */
    public PatientRecord() {
        super(Patient.PATIENT);
    }

    /**
     * Create a detached, initialised PatientRecord
     */
    public PatientRecord(Integer id, String name, String mobile, String patientCode, String identityNo, Byte identityType, String treatmentNo, Byte areaType, Byte sex, Date birthday, String diseaseHistory, String allergyHistory, String memo, Byte isDelete, Timestamp createTime, Timestamp updateTime) {
        super(Patient.PATIENT);

        set(0, id);
        set(1, name);
        set(2, mobile);
        set(3, patientCode);
        set(4, identityNo);
        set(5, identityType);
        set(6, treatmentNo);
        set(7, areaType);
        set(8, sex);
        set(9, birthday);
        set(10, diseaseHistory);
        set(11, allergyHistory);
        set(12, memo);
        set(13, isDelete);
        set(14, createTime);
        set(15, updateTime);
    }
}
