/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables.records;


import com.vpu.mp.db.shop.tables.MpVisitPage;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MpVisitPageRecord extends UpdatableRecordImpl<MpVisitPageRecord> implements Record12<Integer, String, String, Integer, Integer, Double, Integer, Integer, Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -973326114;

    /**
     * Setter for <code>jmini_shop_4748160.b2c_mp_visit_page.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>jmini_shop_4748160.b2c_mp_visit_page.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>jmini_shop_4748160.b2c_mp_visit_page.ref_date</code>. 时间，如："20170313"
     */
    public void setRefDate(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jmini_shop_4748160.b2c_mp_visit_page.ref_date</code>. 时间，如："20170313"
     */
    public String getRefDate() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jmini_shop_4748160.b2c_mp_visit_page.page_path</code>.
     */
    public void setPagePath(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jmini_shop_4748160.b2c_mp_visit_page.page_path</code>.
     */
    public String getPagePath() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jmini_shop_4748160.b2c_mp_visit_page.page_visit_pv</code>. 访问次数
     */
    public void setPageVisitPv(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>jmini_shop_4748160.b2c_mp_visit_page.page_visit_pv</code>. 访问次数
     */
    public Integer getPageVisitPv() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>jmini_shop_4748160.b2c_mp_visit_page.page_visit_uv</code>. 访问人数
     */
    public void setPageVisitUv(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>jmini_shop_4748160.b2c_mp_visit_page.page_visit_uv</code>. 访问人数
     */
    public Integer getPageVisitUv() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>jmini_shop_4748160.b2c_mp_visit_page.page_staytime_pv</code>. 人均停留时长 (浮点型，单位：秒)
     */
    public void setPageStaytimePv(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>jmini_shop_4748160.b2c_mp_visit_page.page_staytime_pv</code>. 人均停留时长 (浮点型，单位：秒)
     */
    public Double getPageStaytimePv() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>jmini_shop_4748160.b2c_mp_visit_page.entrypage_pv</code>. 进入页次数
     */
    public void setEntrypagePv(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>jmini_shop_4748160.b2c_mp_visit_page.entrypage_pv</code>. 进入页次数
     */
    public Integer getEntrypagePv() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>jmini_shop_4748160.b2c_mp_visit_page.exitpage_pv</code>. 退出页次数
     */
    public void setExitpagePv(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>jmini_shop_4748160.b2c_mp_visit_page.exitpage_pv</code>. 退出页次数
     */
    public Integer getExitpagePv() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>jmini_shop_4748160.b2c_mp_visit_page.page_share_pv</code>. 转发次数
     */
    public void setPageSharePv(Integer value) {
        set(8, value);
    }

    /**
     * Getter for <code>jmini_shop_4748160.b2c_mp_visit_page.page_share_pv</code>. 转发次数
     */
    public Integer getPageSharePv() {
        return (Integer) get(8);
    }

    /**
     * Setter for <code>jmini_shop_4748160.b2c_mp_visit_page.page_share_uv</code>. 转发人数
     */
    public void setPageShareUv(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>jmini_shop_4748160.b2c_mp_visit_page.page_share_uv</code>. 转发人数
     */
    public Integer getPageShareUv() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>jmini_shop_4748160.b2c_mp_visit_page.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(10, value);
    }

    /**
     * Getter for <code>jmini_shop_4748160.b2c_mp_visit_page.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(10);
    }

    /**
     * Setter for <code>jmini_shop_4748160.b2c_mp_visit_page.update_time</code>. 最后修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>jmini_shop_4748160.b2c_mp_visit_page.update_time</code>. 最后修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, Integer, Integer, Double, Integer, Integer, Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, String, String, Integer, Integer, Double, Integer, Integer, Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return MpVisitPage.MP_VISIT_PAGE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return MpVisitPage.MP_VISIT_PAGE.REF_DATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return MpVisitPage.MP_VISIT_PAGE.PAGE_PATH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return MpVisitPage.MP_VISIT_PAGE.PAGE_VISIT_PV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return MpVisitPage.MP_VISIT_PAGE.PAGE_VISIT_UV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return MpVisitPage.MP_VISIT_PAGE.PAGE_STAYTIME_PV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return MpVisitPage.MP_VISIT_PAGE.ENTRYPAGE_PV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return MpVisitPage.MP_VISIT_PAGE.EXITPAGE_PV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field9() {
        return MpVisitPage.MP_VISIT_PAGE.PAGE_SHARE_PV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field10() {
        return MpVisitPage.MP_VISIT_PAGE.PAGE_SHARE_UV;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field11() {
        return MpVisitPage.MP_VISIT_PAGE.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return MpVisitPage.MP_VISIT_PAGE.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getRefDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPagePath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getPageVisitPv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getPageVisitUv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getPageStaytimePv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getEntrypagePv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getExitpagePv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component9() {
        return getPageSharePv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component10() {
        return getPageShareUv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component11() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRefDate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPagePath();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPageVisitPv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getPageVisitUv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getPageStaytimePv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getEntrypagePv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getExitpagePv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value9() {
        return getPageSharePv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value10() {
        return getPageShareUv();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value11() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MpVisitPageRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MpVisitPageRecord value2(String value) {
        setRefDate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MpVisitPageRecord value3(String value) {
        setPagePath(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MpVisitPageRecord value4(Integer value) {
        setPageVisitPv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MpVisitPageRecord value5(Integer value) {
        setPageVisitUv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MpVisitPageRecord value6(Double value) {
        setPageStaytimePv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MpVisitPageRecord value7(Integer value) {
        setEntrypagePv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MpVisitPageRecord value8(Integer value) {
        setExitpagePv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MpVisitPageRecord value9(Integer value) {
        setPageSharePv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MpVisitPageRecord value10(Integer value) {
        setPageShareUv(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MpVisitPageRecord value11(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MpVisitPageRecord value12(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MpVisitPageRecord values(Integer value1, String value2, String value3, Integer value4, Integer value5, Double value6, Integer value7, Integer value8, Integer value9, Integer value10, Timestamp value11, Timestamp value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MpVisitPageRecord
     */
    public MpVisitPageRecord() {
        super(MpVisitPage.MP_VISIT_PAGE);
    }

    /**
     * Create a detached, initialised MpVisitPageRecord
     */
    public MpVisitPageRecord(Integer id, String refDate, String pagePath, Integer pageVisitPv, Integer pageVisitUv, Double pageStaytimePv, Integer entrypagePv, Integer exitpagePv, Integer pageSharePv, Integer pageShareUv, Timestamp createTime, Timestamp updateTime) {
        super(MpVisitPage.MP_VISIT_PAGE);

        set(0, id);
        set(1, refDate);
        set(2, pagePath);
        set(3, pageVisitPv);
        set(4, pageVisitUv);
        set(5, pageStaytimePv);
        set(6, entrypagePv);
        set(7, exitpagePv);
        set(8, pageSharePv);
        set(9, pageShareUv);
        set(10, createTime);
        set(11, updateTime);
    }
}
