/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables.records;


import com.vpu.mp.db.shop.tables.UserImportDetail;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserImportDetailRecord extends UpdatableRecordImpl<UserImportDetailRecord> implements Record22<Integer, Integer, String, String, String, Integer, String, String, String, String, String, String, String, String, String, String, BigDecimal, String, String, Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1918740605;

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.batch_id</code>. 主表id
     */
    public void setBatchId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.batch_id</code>. 主表id
     */
    public Integer getBatchId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.mobile</code>. 手机号
     */
    public void setMobile(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.mobile</code>. 手机号
     */
    public String getMobile() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.name</code>. 姓名
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.name</code>. 姓名
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.invite_user_mobile</code>. 邀请人手机号
     */
    public void setInviteUserMobile(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.invite_user_mobile</code>. 邀请人手机号
     */
    public String getInviteUserMobile() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.score</code>. 积分
     */
    public void setScore(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.score</code>. 积分
     */
    public Integer getScore() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.sex</code>. 性别： 女f 男m
     */
    public void setSex(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.sex</code>. 性别： 女f 男m
     */
    public String getSex() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.birthday</code>. 生日
     */
    public void setBirthday(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.birthday</code>. 生日
     */
    public String getBirthday() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.province</code>. 省
     */
    public void setProvince(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.province</code>. 省
     */
    public String getProvince() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.city</code>. 市
     */
    public void setCity(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.city</code>. 市
     */
    public String getCity() {
        return (String) get(9);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.district</code>. 区
     */
    public void setDistrict(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.district</code>. 区
     */
    public String getDistrict() {
        return (String) get(10);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.address</code>. 地址
     */
    public void setAddress(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.address</code>. 地址
     */
    public String getAddress() {
        return (String) get(11);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.id_number</code>. 身份证号
     */
    public void setIdNumber(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.id_number</code>. 身份证号
     */
    public String getIdNumber() {
        return (String) get(12);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.education</code>. 教育程度
     */
    public void setEducation(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.education</code>. 教育程度
     */
    public String getEducation() {
        return (String) get(13);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.industry</code>. 所在行业
     */
    public void setIndustry(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.industry</code>. 所在行业
     */
    public String getIndustry() {
        return (String) get(14);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.marriage</code>. 婚姻状况
     */
    public void setMarriage(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.marriage</code>. 婚姻状况
     */
    public String getMarriage() {
        return (String) get(15);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.income</code>. 月收入
     */
    public void setIncome(BigDecimal value) {
        set(16, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.income</code>. 月收入
     */
    public BigDecimal getIncome() {
        return (BigDecimal) get(16);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.error_msg</code>. 错误内容
     */
    public void setErrorMsg(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.error_msg</code>. 错误内容
     */
    public String getErrorMsg() {
        return (String) get(17);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.card_id</code>. 会员卡id
     */
    public void setCardId(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.card_id</code>. 会员卡id
     */
    public String getCardId() {
        return (String) get(18);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.is_activate</code>. 是否已激活
     */
    public void setIsActivate(Byte value) {
        set(19, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.is_activate</code>. 是否已激活
     */
    public Byte getIsActivate() {
        return (Byte) get(19);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.create_time</code>.
     */
    public void setCreateTime(Timestamp value) {
        set(20, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.create_time</code>.
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(20);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import_detail.update_time</code>. 最后修改时间
     */
    public void setUpdateTime(Timestamp value) {
        set(21, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import_detail.update_time</code>. 最后修改时间
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record22 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<Integer, Integer, String, String, String, Integer, String, String, String, String, String, String, String, String, String, String, BigDecimal, String, String, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<Integer, Integer, String, String, String, Integer, String, String, String, String, String, String, String, String, String, String, BigDecimal, String, String, Byte, Timestamp, Timestamp> valuesRow() {
        return (Row22) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return UserImportDetail.USER_IMPORT_DETAIL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return UserImportDetail.USER_IMPORT_DETAIL.BATCH_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return UserImportDetail.USER_IMPORT_DETAIL.MOBILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return UserImportDetail.USER_IMPORT_DETAIL.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return UserImportDetail.USER_IMPORT_DETAIL.INVITE_USER_MOBILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return UserImportDetail.USER_IMPORT_DETAIL.SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return UserImportDetail.USER_IMPORT_DETAIL.SEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return UserImportDetail.USER_IMPORT_DETAIL.BIRTHDAY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return UserImportDetail.USER_IMPORT_DETAIL.PROVINCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return UserImportDetail.USER_IMPORT_DETAIL.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return UserImportDetail.USER_IMPORT_DETAIL.DISTRICT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return UserImportDetail.USER_IMPORT_DETAIL.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return UserImportDetail.USER_IMPORT_DETAIL.ID_NUMBER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return UserImportDetail.USER_IMPORT_DETAIL.EDUCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return UserImportDetail.USER_IMPORT_DETAIL.INDUSTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field16() {
        return UserImportDetail.USER_IMPORT_DETAIL.MARRIAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field17() {
        return UserImportDetail.USER_IMPORT_DETAIL.INCOME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field18() {
        return UserImportDetail.USER_IMPORT_DETAIL.ERROR_MSG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field19() {
        return UserImportDetail.USER_IMPORT_DETAIL.CARD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field20() {
        return UserImportDetail.USER_IMPORT_DETAIL.IS_ACTIVATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field21() {
        return UserImportDetail.USER_IMPORT_DETAIL.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field22() {
        return UserImportDetail.USER_IMPORT_DETAIL.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getBatchId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getInviteUserMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getProvince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getDistrict();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getIdNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getEducation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getIndustry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component16() {
        return getMarriage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component17() {
        return getIncome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component18() {
        return getErrorMsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component19() {
        return getCardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component20() {
        return getIsActivate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component21() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component22() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getBatchId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getInviteUserMobile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getBirthday();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getProvince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getDistrict();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getIdNumber();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getEducation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getIndustry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value16() {
        return getMarriage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value17() {
        return getIncome();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value18() {
        return getErrorMsg();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value19() {
        return getCardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value20() {
        return getIsActivate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value21() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value22() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value2(Integer value) {
        setBatchId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value3(String value) {
        setMobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value4(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value5(String value) {
        setInviteUserMobile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value6(Integer value) {
        setScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value7(String value) {
        setSex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value8(String value) {
        setBirthday(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value9(String value) {
        setProvince(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value10(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value11(String value) {
        setDistrict(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value12(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value13(String value) {
        setIdNumber(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value14(String value) {
        setEducation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value15(String value) {
        setIndustry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value16(String value) {
        setMarriage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value17(BigDecimal value) {
        setIncome(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value18(String value) {
        setErrorMsg(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value19(String value) {
        setCardId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value20(Byte value) {
        setIsActivate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value21(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord value22(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserImportDetailRecord values(Integer value1, Integer value2, String value3, String value4, String value5, Integer value6, String value7, String value8, String value9, String value10, String value11, String value12, String value13, String value14, String value15, String value16, BigDecimal value17, String value18, String value19, Byte value20, Timestamp value21, Timestamp value22) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        value22(value22);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserImportDetailRecord
     */
    public UserImportDetailRecord() {
        super(UserImportDetail.USER_IMPORT_DETAIL);
    }

    /**
     * Create a detached, initialised UserImportDetailRecord
     */
    public UserImportDetailRecord(Integer id, Integer batchId, String mobile, String name, String inviteUserMobile, Integer score, String sex, String birthday, String province, String city, String district, String address, String idNumber, String education, String industry, String marriage, BigDecimal income, String errorMsg, String cardId, Byte isActivate, Timestamp createTime, Timestamp updateTime) {
        super(UserImportDetail.USER_IMPORT_DETAIL);

        set(0, id);
        set(1, batchId);
        set(2, mobile);
        set(3, name);
        set(4, inviteUserMobile);
        set(5, score);
        set(6, sex);
        set(7, birthday);
        set(8, province);
        set(9, city);
        set(10, district);
        set(11, address);
        set(12, idNumber);
        set(13, education);
        set(14, industry);
        set(15, marriage);
        set(16, income);
        set(17, errorMsg);
        set(18, cardId);
        set(19, isActivate);
        set(20, createTime);
        set(21, updateTime);
    }
}
