/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables.records;


import com.vpu.mp.db.shop.tables.B2cGoodsImg;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cGoodsImgRecord extends UpdatableRecordImpl<B2cGoodsImgRecord> implements Record4<UInteger, UInteger, String, String> {

    private static final long serialVersionUID = -735521566;

    /**
     * Setter for <code>mini_shop_471752.b2c_goods_img.img_id</code>.
     */
    public void setImgId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_goods_img.img_id</code>.
     */
    public UInteger getImgId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_goods_img.goods_id</code>.
     */
    public void setGoodsId(UInteger value) {
        set(1, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_goods_img.goods_id</code>.
     */
    public UInteger getGoodsId() {
        return (UInteger) get(1);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_goods_img.img_url</code>.
     */
    public void setImgUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_goods_img.img_url</code>.
     */
    public String getImgUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_goods_img.img_desc</code>.
     */
    public void setImgDesc(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_goods_img.img_desc</code>.
     */
    public String getImgDesc() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, UInteger, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<UInteger, UInteger, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return B2cGoodsImg.B2C_GOODS_IMG.IMG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field2() {
        return B2cGoodsImg.B2C_GOODS_IMG.GOODS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return B2cGoodsImg.B2C_GOODS_IMG.IMG_URL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return B2cGoodsImg.B2C_GOODS_IMG.IMG_DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getImgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component2() {
        return getGoodsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getImgUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getImgDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getImgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value2() {
        return getGoodsId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getImgUrl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getImgDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cGoodsImgRecord value1(UInteger value) {
        setImgId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cGoodsImgRecord value2(UInteger value) {
        setGoodsId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cGoodsImgRecord value3(String value) {
        setImgUrl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cGoodsImgRecord value4(String value) {
        setImgDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cGoodsImgRecord values(UInteger value1, UInteger value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached B2cGoodsImgRecord
     */
    public B2cGoodsImgRecord() {
        super(B2cGoodsImg.B2C_GOODS_IMG);
    }

    /**
     * Create a detached, initialised B2cGoodsImgRecord
     */
    public B2cGoodsImgRecord(UInteger imgId, UInteger goodsId, String imgUrl, String imgDesc) {
        super(B2cGoodsImg.B2C_GOODS_IMG);

        set(0, imgId);
        set(1, goodsId);
        set(2, imgUrl);
        set(3, imgDesc);
    }
}
