/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables.records;


import com.vpu.mp.db.shop.tables.B2cMpUser;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cMpUserRecord extends UpdatableRecordImpl<B2cMpUserRecord> implements Record18<UInteger, String, String, String, Byte, String, String, String, String, String, String, String, Double, Double, Double, Timestamp, Timestamp, Integer> {

    private static final long serialVersionUID = 167270940;

    /**
     * Setter for <code>mini_shop_471752.b2c_mp_user.mp_user_id</code>.
     */
    public void setMpUserId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_mp_user.mp_user_id</code>.
     */
    public UInteger getMpUserId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_mp_user.app_id</code>. 小程序appId
     */
    public void setAppId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_mp_user.app_id</code>. 小程序appId
     */
    public String getAppId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_mp_user.openid</code>. 用户的标识，对当前公众号唯一
     */
    public void setOpenid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_mp_user.openid</code>. 用户的标识，对当前公众号唯一
     */
    public String getOpenid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_mp_user.nickname</code>.
     */
    public void setNickname(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_mp_user.nickname</code>.
     */
    public String getNickname() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_mp_user.gender</code>. 用户的性别，值为1时是男性，值为2时是女性，值为0时是未知
     */
    public void setGender(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_mp_user.gender</code>. 用户的性别，值为1时是男性，值为2时是女性，值为0时是未知
     */
    public Byte getGender() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_mp_user.language</code>. 用户的语言，简体中文为zh_CN
     */
    public void setLanguage(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_mp_user.language</code>. 用户的语言，简体中文为zh_CN
     */
    public String getLanguage() {
        return (String) get(5);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_mp_user.city</code>. 用户所在城市
     */
    public void setCity(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_mp_user.city</code>. 用户所在城市
     */
    public String getCity() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_mp_user.province</code>. 用户所在省份
     */
    public void setProvince(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_mp_user.province</code>. 用户所在省份
     */
    public String getProvince() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_mp_user.country</code>. 用户所在国家
     */
    public void setCountry(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_mp_user.country</code>. 用户所在国家
     */
    public String getCountry() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_mp_user.avatarUrl</code>. 用户头像，最后一个数值代表正方形头像大小（有0、46、64、96、132数值可选，0代表640*640正方形头像），用户没有头像时该项为空。若用户更换头像，原有头像URL将失效。
     */
    public void setAvatarurl(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_mp_user.avatarUrl</code>. 用户头像，最后一个数值代表正方形头像大小（有0、46、64、96、132数值可选，0代表640*640正方形头像），用户没有头像时该项为空。若用户更换头像，原有头像URL将失效。
     */
    public String getAvatarurl() {
        return (String) get(9);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_mp_user.unionid</code>. 只有在用户绑定到微信开放平台帐号后，才会出现该字段
     */
    public void setUnionid(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_mp_user.unionid</code>. 只有在用户绑定到微信开放平台帐号后，才会出现该字段
     */
    public String getUnionid() {
        return (String) get(10);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_mp_user.user_memo</code>. 备注
     */
    public void setUserMemo(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_mp_user.user_memo</code>. 备注
     */
    public String getUserMemo() {
        return (String) get(11);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_mp_user.latitude</code>. 地理位置纬度
     */
    public void setLatitude(Double value) {
        set(12, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_mp_user.latitude</code>. 地理位置纬度
     */
    public Double getLatitude() {
        return (Double) get(12);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_mp_user.longitude</code>. 地理位置经度
     */
    public void setLongitude(Double value) {
        set(13, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_mp_user.longitude</code>. 地理位置经度
     */
    public Double getLongitude() {
        return (Double) get(13);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_mp_user.precision</code>. 地理位置精度
     */
    public void setPrecision(Double value) {
        set(14, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_mp_user.precision</code>. 地理位置精度
     */
    public Double getPrecision() {
        return (Double) get(14);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_mp_user.last_up_loc_time</code>. 最后记录位置时间
     */
    public void setLastUpLocTime(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_mp_user.last_up_loc_time</code>. 最后记录位置时间
     */
    public Timestamp getLastUpLocTime() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_mp_user.create_time</code>. 创建时间
     */
    public void setCreateTime(Timestamp value) {
        set(16, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_mp_user.create_time</code>. 创建时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(16);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_mp_user.user_id</code>. 关联用户ID
     */
    public void setUserId(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_mp_user.user_id</code>. 关联用户ID
     */
    public Integer getUserId() {
        return (Integer) get(17);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record18 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<UInteger, String, String, String, Byte, String, String, String, String, String, String, String, Double, Double, Double, Timestamp, Timestamp, Integer> fieldsRow() {
        return (Row18) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row18<UInteger, String, String, String, Byte, String, String, String, String, String, String, String, Double, Double, Double, Timestamp, Timestamp, Integer> valuesRow() {
        return (Row18) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return B2cMpUser.B2C_MP_USER.MP_USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return B2cMpUser.B2C_MP_USER.APP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return B2cMpUser.B2C_MP_USER.OPENID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return B2cMpUser.B2C_MP_USER.NICKNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return B2cMpUser.B2C_MP_USER.GENDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return B2cMpUser.B2C_MP_USER.LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return B2cMpUser.B2C_MP_USER.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return B2cMpUser.B2C_MP_USER.PROVINCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return B2cMpUser.B2C_MP_USER.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return B2cMpUser.B2C_MP_USER.AVATARURL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return B2cMpUser.B2C_MP_USER.UNIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return B2cMpUser.B2C_MP_USER.USER_MEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field13() {
        return B2cMpUser.B2C_MP_USER.LATITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field14() {
        return B2cMpUser.B2C_MP_USER.LONGITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field15() {
        return B2cMpUser.B2C_MP_USER.PRECISION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field16() {
        return B2cMpUser.B2C_MP_USER.LAST_UP_LOC_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field17() {
        return B2cMpUser.B2C_MP_USER.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field18() {
        return B2cMpUser.B2C_MP_USER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getMpUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOpenid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getProvince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getAvatarurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getUnionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getUserMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component13() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component14() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component15() {
        return getPrecision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component16() {
        return getLastUpLocTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component17() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component18() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getMpUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOpenid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getGender();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getProvince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getAvatarurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getUnionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getUserMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value13() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value14() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value15() {
        return getPrecision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value16() {
        return getLastUpLocTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value17() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value18() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpUserRecord value1(UInteger value) {
        setMpUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpUserRecord value2(String value) {
        setAppId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpUserRecord value3(String value) {
        setOpenid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpUserRecord value4(String value) {
        setNickname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpUserRecord value5(Byte value) {
        setGender(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpUserRecord value6(String value) {
        setLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpUserRecord value7(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpUserRecord value8(String value) {
        setProvince(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpUserRecord value9(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpUserRecord value10(String value) {
        setAvatarurl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpUserRecord value11(String value) {
        setUnionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpUserRecord value12(String value) {
        setUserMemo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpUserRecord value13(Double value) {
        setLatitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpUserRecord value14(Double value) {
        setLongitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpUserRecord value15(Double value) {
        setPrecision(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpUserRecord value16(Timestamp value) {
        setLastUpLocTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpUserRecord value17(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpUserRecord value18(Integer value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpUserRecord values(UInteger value1, String value2, String value3, String value4, Byte value5, String value6, String value7, String value8, String value9, String value10, String value11, String value12, Double value13, Double value14, Double value15, Timestamp value16, Timestamp value17, Integer value18) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached B2cMpUserRecord
     */
    public B2cMpUserRecord() {
        super(B2cMpUser.B2C_MP_USER);
    }

    /**
     * Create a detached, initialised B2cMpUserRecord
     */
    public B2cMpUserRecord(UInteger mpUserId, String appId, String openid, String nickname, Byte gender, String language, String city, String province, String country, String avatarurl, String unionid, String userMemo, Double latitude, Double longitude, Double precision, Timestamp lastUpLocTime, Timestamp createTime, Integer userId) {
        super(B2cMpUser.B2C_MP_USER);

        set(0, mpUserId);
        set(1, appId);
        set(2, openid);
        set(3, nickname);
        set(4, gender);
        set(5, language);
        set(6, city);
        set(7, province);
        set(8, country);
        set(9, avatarurl);
        set(10, unionid);
        set(11, userMemo);
        set(12, latitude);
        set(13, longitude);
        set(14, precision);
        set(15, lastUpLocTime);
        set(16, createTime);
        set(17, userId);
    }
}
