/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables.records;


import com.vpu.mp.db.shop.tables.B2cShipping;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cShippingRecord extends UpdatableRecordImpl<B2cShippingRecord> implements Record10<UByte, String, String, String, String, UByte, UByte, String, Byte, UByte> {

    private static final long serialVersionUID = 1655971421;

    /**
     * Setter for <code>mini_shop_471752.b2c_shipping.shipping_id</code>.
     */
    public void setShippingId(UByte value) {
        set(0, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_shipping.shipping_id</code>.
     */
    public UByte getShippingId() {
        return (UByte) get(0);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_shipping.shipping_code</code>.
     */
    public void setShippingCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_shipping.shipping_code</code>.
     */
    public String getShippingCode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_shipping.shipping_name</code>.
     */
    public void setShippingName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_shipping.shipping_name</code>.
     */
    public String getShippingName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_shipping.shipping_desc</code>.
     */
    public void setShippingDesc(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_shipping.shipping_desc</code>.
     */
    public String getShippingDesc() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_shipping.insure</code>.
     */
    public void setInsure(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_shipping.insure</code>.
     */
    public String getInsure() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_shipping.support_cod</code>.
     */
    public void setSupportCod(UByte value) {
        set(5, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_shipping.support_cod</code>.
     */
    public UByte getSupportCod() {
        return (UByte) get(5);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_shipping.enabled</code>.
     */
    public void setEnabled(UByte value) {
        set(6, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_shipping.enabled</code>.
     */
    public UByte getEnabled() {
        return (UByte) get(6);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_shipping.shipping_print</code>.
     */
    public void setShippingPrint(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_shipping.shipping_print</code>.
     */
    public String getShippingPrint() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_shipping.print_model</code>.
     */
    public void setPrintModel(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_shipping.print_model</code>.
     */
    public Byte getPrintModel() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_shipping.shipping_order</code>.
     */
    public void setShippingOrder(UByte value) {
        set(9, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_shipping.shipping_order</code>.
     */
    public UByte getShippingOrder() {
        return (UByte) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UByte> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<UByte, String, String, String, String, UByte, UByte, String, Byte, UByte> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<UByte, String, String, String, String, UByte, UByte, String, Byte, UByte> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field1() {
        return B2cShipping.B2C_SHIPPING.SHIPPING_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return B2cShipping.B2C_SHIPPING.SHIPPING_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return B2cShipping.B2C_SHIPPING.SHIPPING_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return B2cShipping.B2C_SHIPPING.SHIPPING_DESC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return B2cShipping.B2C_SHIPPING.INSURE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field6() {
        return B2cShipping.B2C_SHIPPING.SUPPORT_COD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field7() {
        return B2cShipping.B2C_SHIPPING.ENABLED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return B2cShipping.B2C_SHIPPING.SHIPPING_PRINT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return B2cShipping.B2C_SHIPPING.PRINT_MODEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field10() {
        return B2cShipping.B2C_SHIPPING.SHIPPING_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component1() {
        return getShippingId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getShippingCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getShippingName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getShippingDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getInsure();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component6() {
        return getSupportCod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component7() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getShippingPrint();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component9() {
        return getPrintModel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component10() {
        return getShippingOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value1() {
        return getShippingId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getShippingCode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getShippingName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getShippingDesc();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getInsure();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value6() {
        return getSupportCod();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value7() {
        return getEnabled();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getShippingPrint();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getPrintModel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value10() {
        return getShippingOrder();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cShippingRecord value1(UByte value) {
        setShippingId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cShippingRecord value2(String value) {
        setShippingCode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cShippingRecord value3(String value) {
        setShippingName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cShippingRecord value4(String value) {
        setShippingDesc(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cShippingRecord value5(String value) {
        setInsure(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cShippingRecord value6(UByte value) {
        setSupportCod(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cShippingRecord value7(UByte value) {
        setEnabled(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cShippingRecord value8(String value) {
        setShippingPrint(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cShippingRecord value9(Byte value) {
        setPrintModel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cShippingRecord value10(UByte value) {
        setShippingOrder(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cShippingRecord values(UByte value1, String value2, String value3, String value4, String value5, UByte value6, UByte value7, String value8, Byte value9, UByte value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached B2cShippingRecord
     */
    public B2cShippingRecord() {
        super(B2cShipping.B2C_SHIPPING);
    }

    /**
     * Create a detached, initialised B2cShippingRecord
     */
    public B2cShippingRecord(UByte shippingId, String shippingCode, String shippingName, String shippingDesc, String insure, UByte supportCod, UByte enabled, String shippingPrint, Byte printModel, UByte shippingOrder) {
        super(B2cShipping.B2C_SHIPPING);

        set(0, shippingId);
        set(1, shippingCode);
        set(2, shippingName);
        set(3, shippingDesc);
        set(4, insure);
        set(5, supportCod);
        set(6, enabled);
        set(7, shippingPrint);
        set(8, printModel);
        set(9, shippingOrder);
    }
}
