/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables.records;


import com.vpu.mp.db.shop.tables.B2cServiceRequest;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cServiceRequestRecord extends UpdatableRecordImpl<B2cServiceRequestRecord> implements Record8<ULong, String, String, String, Timestamp, Timestamp, String, String> {

    private static final long serialVersionUID = -241929506;

    /**
     * Setter for <code>mini_shop_471752.b2c_service_request.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_service_request.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_service_request.request_id</code>. 请求requestId
     */
    public void setRequestId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_service_request.request_id</code>. 请求requestId
     */
    public String getRequestId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_service_request.service_name</code>. 服务名
     */
    public void setServiceName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_service_request.service_name</code>. 服务名
     */
    public String getServiceName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_service_request.request_content</code>. 请求内容
     */
    public void setRequestContent(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_service_request.request_content</code>. 请求内容
     */
    public String getRequestContent() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_service_request.request_time</code>. 请求时间
     */
    public void setRequestTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_service_request.request_time</code>. 请求时间
     */
    public Timestamp getRequestTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_service_request.response_time</code>. 响应时间
     */
    public void setResponseTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_service_request.response_time</code>. 响应时间
     */
    public Timestamp getResponseTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_service_request.response_content</code>. 响应内容
     */
    public void setResponseContent(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_service_request.response_content</code>. 响应内容
     */
    public String getResponseContent() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_service_request.ip</code>. 请求ip
     */
    public void setIp(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_service_request.ip</code>. 请求ip
     */
    public String getIp() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<ULong, String, String, String, Timestamp, Timestamp, String, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<ULong, String, String, String, Timestamp, Timestamp, String, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return B2cServiceRequest.B2C_SERVICE_REQUEST.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return B2cServiceRequest.B2C_SERVICE_REQUEST.REQUEST_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return B2cServiceRequest.B2C_SERVICE_REQUEST.SERVICE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return B2cServiceRequest.B2C_SERVICE_REQUEST.REQUEST_CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return B2cServiceRequest.B2C_SERVICE_REQUEST.REQUEST_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return B2cServiceRequest.B2C_SERVICE_REQUEST.RESPONSE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return B2cServiceRequest.B2C_SERVICE_REQUEST.RESPONSE_CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return B2cServiceRequest.B2C_SERVICE_REQUEST.IP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getRequestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getServiceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRequestContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getRequestTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getResponseTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getResponseContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getRequestId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getServiceName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRequestContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getRequestTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getResponseTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getResponseContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getIp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cServiceRequestRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cServiceRequestRecord value2(String value) {
        setRequestId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cServiceRequestRecord value3(String value) {
        setServiceName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cServiceRequestRecord value4(String value) {
        setRequestContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cServiceRequestRecord value5(Timestamp value) {
        setRequestTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cServiceRequestRecord value6(Timestamp value) {
        setResponseTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cServiceRequestRecord value7(String value) {
        setResponseContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cServiceRequestRecord value8(String value) {
        setIp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cServiceRequestRecord values(ULong value1, String value2, String value3, String value4, Timestamp value5, Timestamp value6, String value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached B2cServiceRequestRecord
     */
    public B2cServiceRequestRecord() {
        super(B2cServiceRequest.B2C_SERVICE_REQUEST);
    }

    /**
     * Create a detached, initialised B2cServiceRequestRecord
     */
    public B2cServiceRequestRecord(ULong id, String requestId, String serviceName, String requestContent, Timestamp requestTime, Timestamp responseTime, String responseContent, String ip) {
        super(B2cServiceRequest.B2C_SERVICE_REQUEST);

        set(0, id);
        set(1, requestId);
        set(2, serviceName);
        set(3, requestContent);
        set(4, requestTime);
        set(5, responseTime);
        set(6, responseContent);
        set(7, ip);
    }
}
