/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables.records;


import com.vpu.mp.db.shop.tables.B2cUserGrade;

import java.math.BigDecimal;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record12;
import org.jooq.Row12;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cUserGradeRecord extends UpdatableRecordImpl<B2cUserGradeRecord> implements Record12<Integer, Integer, String, String, Integer, Integer, Integer, Timestamp, Timestamp, Timestamp, BigDecimal, BigDecimal> {

    private static final long serialVersionUID = -1402022149;

    /**
     * Setter for <code>mini_shop_471752.b2c_user_grade.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_grade.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_grade.shop_id</code>. 店铺ID
     */
    public void setShopId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_grade.shop_id</code>. 店铺ID
     */
    public Integer getShopId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_grade.grade</code>. 会员等级：reg:注册,bronze:铜,silver:银,gold:金,diamond:钻石
     */
    public void setGrade(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_grade.grade</code>. 会员等级：reg:注册,bronze:铜,silver:银,gold:金,diamond:钻石
     */
    public String getGrade() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_grade.grade_name</code>. 等级名称
     */
    public void setGradeName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_grade.grade_name</code>. 等级名称
     */
    public String getGradeName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_grade.min_val</code>. 最小成长值
     */
    public void setMinVal(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_grade.min_val</code>. 最小成长值
     */
    public Integer getMinVal() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_grade.max_val</code>. 最大成长史
     */
    public void setMaxVal(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_grade.max_val</code>. 最大成长史
     */
    public Integer getMaxVal() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_grade.reduce</code>. 一年后扣除的成长值
     */
    public void setReduce(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_grade.reduce</code>. 一年后扣除的成长值
     */
    public Integer getReduce() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_grade.in_time</code>.
     */
    public void setInTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_grade.in_time</code>.
     */
    public Timestamp getInTime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_grade.up_time</code>.
     */
    public void setUpTime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_grade.up_time</code>.
     */
    public Timestamp getUpTime() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_grade.settle_time</code>. 结算时间
     */
    public void setSettleTime(Timestamp value) {
        set(9, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_grade.settle_time</code>. 结算时间
     */
    public Timestamp getSettleTime() {
        return (Timestamp) get(9);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_grade.divide</code>. 分成
     */
    public void setDivide(BigDecimal value) {
        set(10, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_grade.divide</code>. 分成
     */
    public BigDecimal getDivide() {
        return (BigDecimal) get(10);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_grade.discount</code>. 折扣
     */
    public void setDiscount(BigDecimal value) {
        set(11, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_grade.discount</code>. 折扣
     */
    public BigDecimal getDiscount() {
        return (BigDecimal) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record12 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Integer, String, String, Integer, Integer, Integer, Timestamp, Timestamp, Timestamp, BigDecimal, BigDecimal> fieldsRow() {
        return (Row12) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row12<Integer, Integer, String, String, Integer, Integer, Integer, Timestamp, Timestamp, Timestamp, BigDecimal, BigDecimal> valuesRow() {
        return (Row12) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return B2cUserGrade.B2C_USER_GRADE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return B2cUserGrade.B2C_USER_GRADE.SHOP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return B2cUserGrade.B2C_USER_GRADE.GRADE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return B2cUserGrade.B2C_USER_GRADE.GRADE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return B2cUserGrade.B2C_USER_GRADE.MIN_VAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return B2cUserGrade.B2C_USER_GRADE.MAX_VAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return B2cUserGrade.B2C_USER_GRADE.REDUCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return B2cUserGrade.B2C_USER_GRADE.IN_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return B2cUserGrade.B2C_USER_GRADE.UP_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field10() {
        return B2cUserGrade.B2C_USER_GRADE.SETTLE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field11() {
        return B2cUserGrade.B2C_USER_GRADE.DIVIDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field12() {
        return B2cUserGrade.B2C_USER_GRADE.DISCOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getShopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getGrade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getGradeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getMinVal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getMaxVal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getReduce();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getInTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getUpTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component10() {
        return getSettleTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component11() {
        return getDivide();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component12() {
        return getDiscount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getShopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getGrade();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getGradeName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getMinVal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getMaxVal();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getReduce();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getInTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value10() {
        return getSettleTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value11() {
        return getDivide();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value12() {
        return getDiscount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserGradeRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserGradeRecord value2(Integer value) {
        setShopId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserGradeRecord value3(String value) {
        setGrade(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserGradeRecord value4(String value) {
        setGradeName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserGradeRecord value5(Integer value) {
        setMinVal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserGradeRecord value6(Integer value) {
        setMaxVal(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserGradeRecord value7(Integer value) {
        setReduce(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserGradeRecord value8(Timestamp value) {
        setInTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserGradeRecord value9(Timestamp value) {
        setUpTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserGradeRecord value10(Timestamp value) {
        setSettleTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserGradeRecord value11(BigDecimal value) {
        setDivide(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserGradeRecord value12(BigDecimal value) {
        setDiscount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserGradeRecord values(Integer value1, Integer value2, String value3, String value4, Integer value5, Integer value6, Integer value7, Timestamp value8, Timestamp value9, Timestamp value10, BigDecimal value11, BigDecimal value12) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached B2cUserGradeRecord
     */
    public B2cUserGradeRecord() {
        super(B2cUserGrade.B2C_USER_GRADE);
    }

    /**
     * Create a detached, initialised B2cUserGradeRecord
     */
    public B2cUserGradeRecord(Integer id, Integer shopId, String grade, String gradeName, Integer minVal, Integer maxVal, Integer reduce, Timestamp inTime, Timestamp upTime, Timestamp settleTime, BigDecimal divide, BigDecimal discount) {
        super(B2cUserGrade.B2C_USER_GRADE);

        set(0, id);
        set(1, shopId);
        set(2, grade);
        set(3, gradeName);
        set(4, minVal);
        set(5, maxVal);
        set(6, reduce);
        set(7, inTime);
        set(8, upTime);
        set(9, settleTime);
        set(10, divide);
        set(11, discount);
    }
}
