/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables.records;


import com.vpu.mp.db.shop.tables.B2cUserImport;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cUserImportRecord extends UpdatableRecordImpl<B2cUserImportRecord> implements Record8<Integer, String, Integer, Integer, Timestamp, Timestamp, Byte, Timestamp> {

    private static final long serialVersionUID = 2114447431;

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import.card_id</code>. 会员卡ID
     */
    public void setCardId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import.card_id</code>. 会员卡ID
     */
    public String getCardId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import.total_num</code>. 总数
     */
    public void setTotalNum(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import.total_num</code>. 总数
     */
    public Integer getTotalNum() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import.success_num</code>. 成功数
     */
    public void setSuccessNum(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import.success_num</code>. 成功数
     */
    public Integer getSuccessNum() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import.add_time</code>.
     */
    public void setAddTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import.add_time</code>.
     */
    public Timestamp getAddTime() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import.del_flag</code>.
     */
    public void setDelFlag(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import.del_flag</code>.
     */
    public Byte getDelFlag() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>mini_shop_471752.b2c_user_import.del_time</code>.
     */
    public void setDelTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>mini_shop_471752.b2c_user_import.del_time</code>.
     */
    public Timestamp getDelTime() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Integer, Integer, Timestamp, Timestamp, Byte, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, Integer, Integer, Timestamp, Timestamp, Byte, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return B2cUserImport.B2C_USER_IMPORT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return B2cUserImport.B2C_USER_IMPORT.CARD_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return B2cUserImport.B2C_USER_IMPORT.TOTAL_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return B2cUserImport.B2C_USER_IMPORT.SUCCESS_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return B2cUserImport.B2C_USER_IMPORT.ADD_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return B2cUserImport.B2C_USER_IMPORT.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return B2cUserImport.B2C_USER_IMPORT.DEL_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return B2cUserImport.B2C_USER_IMPORT.DEL_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getTotalNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getSuccessNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getAddTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getDelTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCardId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTotalNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getSuccessNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getAddTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getDelFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getDelTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserImportRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserImportRecord value2(String value) {
        setCardId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserImportRecord value3(Integer value) {
        setTotalNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserImportRecord value4(Integer value) {
        setSuccessNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserImportRecord value5(Timestamp value) {
        setAddTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserImportRecord value6(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserImportRecord value7(Byte value) {
        setDelFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserImportRecord value8(Timestamp value) {
        setDelTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cUserImportRecord values(Integer value1, String value2, Integer value3, Integer value4, Timestamp value5, Timestamp value6, Byte value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached B2cUserImportRecord
     */
    public B2cUserImportRecord() {
        super(B2cUserImport.B2C_USER_IMPORT);
    }

    /**
     * Create a detached, initialised B2cUserImportRecord
     */
    public B2cUserImportRecord(Integer id, String cardId, Integer totalNum, Integer successNum, Timestamp addTime, Timestamp updateTime, Byte delFlag, Timestamp delTime) {
        super(B2cUserImport.B2C_USER_IMPORT);

        set(0, id);
        set(1, cardId);
        set(2, totalNum);
        set(3, successNum);
        set(4, addTime);
        set(5, updateTime);
        set(6, delFlag);
        set(7, delTime);
    }
}
