/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables.records;


import com.vpu.mp.db.shop.tables.WxpUser;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record22;
import org.jooq.Row22;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class WxpUserRecord extends UpdatableRecordImpl<WxpUserRecord> implements Record22<UInteger, Integer, String, Byte, String, Byte, String, String, String, String, String, Timestamp, String, Integer, String, Timestamp, Integer, Byte, Double, Double, Double, Timestamp> {

    private static final long serialVersionUID = 482580056;

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.user_id</code>.
     */
    public void setUserId(UInteger value) {
        set(0, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.user_id</code>.
     */
    public UInteger getUserId() {
        return (UInteger) get(0);
    }

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.shop_id</code>. 店铺ID
     */
    public void setShopId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.shop_id</code>. 店铺ID
     */
    public Integer getShopId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.openid</code>. 用户的标识，对当前公众号唯一
     */
    public void setOpenid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.openid</code>. 用户的标识，对当前公众号唯一
     */
    public String getOpenid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.subscribe</code>. 是否订阅，为0代表此用户没有关注该公众号，拉取不到其余信息。
     */
    public void setSubscribe(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.subscribe</code>. 是否订阅，为0代表此用户没有关注该公众号，拉取不到其余信息。
     */
    public Byte getSubscribe() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.nickname</code>.
     */
    public void setNickname(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.nickname</code>.
     */
    public String getNickname() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.sex</code>. 用户的性别，值为1时是男性，值为2时是女性，值为0时是未知
     */
    public void setSex(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.sex</code>. 用户的性别，值为1时是男性，值为2时是女性，值为0时是未知
     */
    public Byte getSex() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.language</code>. 用户的语言，简体中文为zh_CN
     */
    public void setLanguage(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.language</code>. 用户的语言，简体中文为zh_CN
     */
    public String getLanguage() {
        return (String) get(6);
    }

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.city</code>. 用户所在城市
     */
    public void setCity(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.city</code>. 用户所在城市
     */
    public String getCity() {
        return (String) get(7);
    }

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.province</code>. 用户所在省份
     */
    public void setProvince(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.province</code>. 用户所在省份
     */
    public String getProvince() {
        return (String) get(8);
    }

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.country</code>. 用户所在国家
     */
    public void setCountry(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.country</code>. 用户所在国家
     */
    public String getCountry() {
        return (String) get(9);
    }

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.headimgurl</code>. 用户头像，最后一个数值代表正方形头像大小（有0、46、64、96、132数值可选，0代表640*640正方形头像），用户没有头像时该项为空
     */
    public void setHeadimgurl(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.headimgurl</code>. 用户头像，最后一个数值代表正方形头像大小（有0、46、64、96、132数值可选，0代表640*640正方形头像），用户没有头像时该项为空
     */
    public String getHeadimgurl() {
        return (String) get(10);
    }

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.subscribe_time</code>. 用户关注时间，如果用户曾多次关注，则取最后关注时间
     */
    public void setSubscribeTime(Timestamp value) {
        set(11, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.subscribe_time</code>. 用户关注时间，如果用户曾多次关注，则取最后关注时间
     */
    public Timestamp getSubscribeTime() {
        return (Timestamp) get(11);
    }

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.unionid</code>. 只有在用户将公众号绑定到微信开放平台帐号后，才会出现该字段
     */
    public void setUnionid(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.unionid</code>. 只有在用户将公众号绑定到微信开放平台帐号后，才会出现该字段
     */
    public String getUnionid() {
        return (String) get(12);
    }

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.group_id</code>. 分组ID,0为默认分组
     */
    public void setGroupId(Integer value) {
        set(13, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.group_id</code>. 分组ID,0为默认分组
     */
    public Integer getGroupId() {
        return (Integer) get(13);
    }

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.user_memo</code>. 备注
     */
    public void setUserMemo(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.user_memo</code>. 备注
     */
    public String getUserMemo() {
        return (String) get(14);
    }

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.last_msg_time</code>. 最后互动时间戳
     */
    public void setLastMsgTime(Timestamp value) {
        set(15, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.last_msg_time</code>. 最后互动时间戳
     */
    public Timestamp getLastMsgTime() {
        return (Timestamp) get(15);
    }

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.micro_id</code>. 所属微信公众号ID,关联b2c_wxp_list的micro_id
     */
    public void setMicroId(Integer value) {
        set(16, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.micro_id</code>. 所属微信公众号ID,关联b2c_wxp_list的micro_id
     */
    public Integer getMicroId() {
        return (Integer) get(16);
    }

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.update_flag</code>. 批量更新标志，为1不更新为取消关注
     */
    public void setUpdateFlag(Byte value) {
        set(17, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.update_flag</code>. 批量更新标志，为1不更新为取消关注
     */
    public Byte getUpdateFlag() {
        return (Byte) get(17);
    }

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.latitude</code>. 地理位置纬度
     */
    public void setLatitude(Double value) {
        set(18, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.latitude</code>. 地理位置纬度
     */
    public Double getLatitude() {
        return (Double) get(18);
    }

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.longitude</code>. 地理位置经度
     */
    public void setLongitude(Double value) {
        set(19, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.longitude</code>. 地理位置经度
     */
    public Double getLongitude() {
        return (Double) get(19);
    }

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.precision</code>. 地理位置精度
     */
    public void setPrecision(Double value) {
        set(20, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.precision</code>. 地理位置精度
     */
    public Double getPrecision() {
        return (Double) get(20);
    }

    /**
     * Setter for <code>mini_shop_1.b2c_wxp_user.last_up_loc_time</code>. 最后记录位置时间
     */
    public void setLastUpLocTime(Timestamp value) {
        set(21, value);
    }

    /**
     * Getter for <code>mini_shop_1.b2c_wxp_user.last_up_loc_time</code>. 最后记录位置时间
     */
    public Timestamp getLastUpLocTime() {
        return (Timestamp) get(21);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UInteger> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record22 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<UInteger, Integer, String, Byte, String, Byte, String, String, String, String, String, Timestamp, String, Integer, String, Timestamp, Integer, Byte, Double, Double, Double, Timestamp> fieldsRow() {
        return (Row22) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row22<UInteger, Integer, String, Byte, String, Byte, String, String, String, String, String, Timestamp, String, Integer, String, Timestamp, Integer, Byte, Double, Double, Double, Timestamp> valuesRow() {
        return (Row22) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field1() {
        return WxpUser.WXP_USER.USER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return WxpUser.WXP_USER.SHOP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return WxpUser.WXP_USER.OPENID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return WxpUser.WXP_USER.SUBSCRIBE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return WxpUser.WXP_USER.NICKNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return WxpUser.WXP_USER.SEX;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return WxpUser.WXP_USER.LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return WxpUser.WXP_USER.CITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return WxpUser.WXP_USER.PROVINCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return WxpUser.WXP_USER.COUNTRY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return WxpUser.WXP_USER.HEADIMGURL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field12() {
        return WxpUser.WXP_USER.SUBSCRIBE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return WxpUser.WXP_USER.UNIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field14() {
        return WxpUser.WXP_USER.GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return WxpUser.WXP_USER.USER_MEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field16() {
        return WxpUser.WXP_USER.LAST_MSG_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field17() {
        return WxpUser.WXP_USER.MICRO_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field18() {
        return WxpUser.WXP_USER.UPDATE_FLAG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field19() {
        return WxpUser.WXP_USER.LATITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field20() {
        return WxpUser.WXP_USER.LONGITUDE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field21() {
        return WxpUser.WXP_USER.PRECISION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field22() {
        return WxpUser.WXP_USER.LAST_UP_LOC_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getShopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getOpenid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getSubscribe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getProvince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getHeadimgurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component12() {
        return getSubscribeTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getUnionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component14() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getUserMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component16() {
        return getLastMsgTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component17() {
        return getMicroId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component18() {
        return getUpdateFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component19() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component20() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component21() {
        return getPrecision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component22() {
        return getLastUpLocTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value1() {
        return getUserId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getShopId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getOpenid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getSubscribe();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getNickname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getSex();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getCity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getProvince();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getCountry();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getHeadimgurl();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value12() {
        return getSubscribeTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getUnionid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value14() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getUserMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value16() {
        return getLastMsgTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value17() {
        return getMicroId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value18() {
        return getUpdateFlag();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value19() {
        return getLatitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value20() {
        return getLongitude();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value21() {
        return getPrecision();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value22() {
        return getLastUpLocTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value1(UInteger value) {
        setUserId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value2(Integer value) {
        setShopId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value3(String value) {
        setOpenid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value4(Byte value) {
        setSubscribe(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value5(String value) {
        setNickname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value6(Byte value) {
        setSex(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value7(String value) {
        setLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value8(String value) {
        setCity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value9(String value) {
        setProvince(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value10(String value) {
        setCountry(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value11(String value) {
        setHeadimgurl(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value12(Timestamp value) {
        setSubscribeTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value13(String value) {
        setUnionid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value14(Integer value) {
        setGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value15(String value) {
        setUserMemo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value16(Timestamp value) {
        setLastMsgTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value17(Integer value) {
        setMicroId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value18(Byte value) {
        setUpdateFlag(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value19(Double value) {
        setLatitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value20(Double value) {
        setLongitude(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value21(Double value) {
        setPrecision(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord value22(Timestamp value) {
        setLastUpLocTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public WxpUserRecord values(UInteger value1, Integer value2, String value3, Byte value4, String value5, Byte value6, String value7, String value8, String value9, String value10, String value11, Timestamp value12, String value13, Integer value14, String value15, Timestamp value16, Integer value17, Byte value18, Double value19, Double value20, Double value21, Timestamp value22) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        value17(value17);
        value18(value18);
        value19(value19);
        value20(value20);
        value21(value21);
        value22(value22);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached WxpUserRecord
     */
    public WxpUserRecord() {
        super(WxpUser.WXP_USER);
    }

    /**
     * Create a detached, initialised WxpUserRecord
     */
    public WxpUserRecord(UInteger userId, Integer shopId, String openid, Byte subscribe, String nickname, Byte sex, String language, String city, String province, String country, String headimgurl, Timestamp subscribeTime, String unionid, Integer groupId, String userMemo, Timestamp lastMsgTime, Integer microId, Byte updateFlag, Double latitude, Double longitude, Double precision, Timestamp lastUpLocTime) {
        super(WxpUser.WXP_USER);

        set(0, userId);
        set(1, shopId);
        set(2, openid);
        set(3, subscribe);
        set(4, nickname);
        set(5, sex);
        set(6, language);
        set(7, city);
        set(8, province);
        set(9, country);
        set(10, headimgurl);
        set(11, subscribeTime);
        set(12, unionid);
        set(13, groupId);
        set(14, userMemo);
        set(15, lastMsgTime);
        set(16, microId);
        set(17, updateFlag);
        set(18, latitude);
        set(19, longitude);
        set(20, precision);
        set(21, lastUpLocTime);
    }
}
