/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables;


import com.vpu.mp.db.shop.Indexes;
import com.vpu.mp.db.shop.Keys;
import com.vpu.mp.db.shop.MiniShop_471752;
import com.vpu.mp.db.shop.tables.records.B2cAttributeNameRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cAttributeName extends TableImpl<B2cAttributeNameRecord> {

    private static final long serialVersionUID = -904200872;

    /**
     * The reference instance of <code>mini_shop_471752.b2c_attribute_name</code>
     */
    public static final B2cAttributeName B2C_ATTRIBUTE_NAME = new B2cAttributeName();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<B2cAttributeNameRecord> getRecordType() {
        return B2cAttributeNameRecord.class;
    }

    /**
     * The column <code>mini_shop_471752.b2c_attribute_name.attr_name_id</code>.
     */
    public final TableField<B2cAttributeNameRecord, Integer> ATTR_NAME_ID = createField("attr_name_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>mini_shop_471752.b2c_attribute_name.attr_type</code>. 0下拉选择，1文本输入
     */
    public final TableField<B2cAttributeNameRecord, Byte> ATTR_TYPE = createField("attr_type", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "0下拉选择，1文本输入");

    /**
     * The column <code>mini_shop_471752.b2c_attribute_name.for_search</code>. 1用于搜索
     */
    public final TableField<B2cAttributeNameRecord, Byte> FOR_SEARCH = createField("for_search", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "1用于搜索");

    /**
     * The column <code>mini_shop_471752.b2c_attribute_name.attr_name</code>. 属性名
     */
    public final TableField<B2cAttributeNameRecord, String> ATTR_NAME = createField("attr_name", org.jooq.impl.SQLDataType.VARCHAR(191).nullable(false), this, "属性名");

    /**
     * The column <code>mini_shop_471752.b2c_attribute_name.attr_id</code>.
     */
    public final TableField<B2cAttributeNameRecord, Integer> ATTR_ID = createField("attr_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>mini_shop_471752.b2c_attribute_name.is_del</code>.
     */
    public final TableField<B2cAttributeNameRecord, Byte> IS_DEL = createField("is_del", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * Create a <code>mini_shop_471752.b2c_attribute_name</code> table reference
     */
    public B2cAttributeName() {
        this(DSL.name("b2c_attribute_name"), null);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_attribute_name</code> table reference
     */
    public B2cAttributeName(String alias) {
        this(DSL.name(alias), B2C_ATTRIBUTE_NAME);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_attribute_name</code> table reference
     */
    public B2cAttributeName(Name alias) {
        this(alias, B2C_ATTRIBUTE_NAME);
    }

    private B2cAttributeName(Name alias, Table<B2cAttributeNameRecord> aliased) {
        this(alias, aliased, null);
    }

    private B2cAttributeName(Name alias, Table<B2cAttributeNameRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> B2cAttributeName(Table<O> child, ForeignKey<O, B2cAttributeNameRecord> key) {
        super(child, key, B2C_ATTRIBUTE_NAME);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MiniShop_471752.MINI_SHOP_471752;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.B2C_ATTRIBUTE_NAME_ATTR_ID, Indexes.B2C_ATTRIBUTE_NAME_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<B2cAttributeNameRecord, Integer> getIdentity() {
        return Keys.IDENTITY_B2C_ATTRIBUTE_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<B2cAttributeNameRecord> getPrimaryKey() {
        return Keys.KEY_B2C_ATTRIBUTE_NAME_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<B2cAttributeNameRecord>> getKeys() {
        return Arrays.<UniqueKey<B2cAttributeNameRecord>>asList(Keys.KEY_B2C_ATTRIBUTE_NAME_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cAttributeName as(String alias) {
        return new B2cAttributeName(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cAttributeName as(Name alias) {
        return new B2cAttributeName(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cAttributeName rename(String name) {
        return new B2cAttributeName(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cAttributeName rename(Name name) {
        return new B2cAttributeName(name, null);
    }
}
