/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables;


import com.vpu.mp.db.shop.Indexes;
import com.vpu.mp.db.shop.Keys;
import com.vpu.mp.db.shop.MiniShop_471752;
import com.vpu.mp.db.shop.tables.records.B2cCardReceiveCodeRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cCardReceiveCode extends TableImpl<B2cCardReceiveCodeRecord> {

    private static final long serialVersionUID = -487220761;

    /**
     * The reference instance of <code>mini_shop_471752.b2c_card_receive_code</code>
     */
    public static final B2cCardReceiveCode B2C_CARD_RECEIVE_CODE = new B2cCardReceiveCode();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<B2cCardReceiveCodeRecord> getRecordType() {
        return B2cCardReceiveCodeRecord.class;
    }

    /**
     * The column <code>mini_shop_471752.b2c_card_receive_code.id</code>.
     */
    public final TableField<B2cCardReceiveCodeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>mini_shop_471752.b2c_card_receive_code.card_id</code>. 卡号ID
     */
    public final TableField<B2cCardReceiveCodeRecord, Integer> CARD_ID = createField("card_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "卡号ID");

    /**
     * The column <code>mini_shop_471752.b2c_card_receive_code.batch_id</code>. 批次ID
     */
    public final TableField<B2cCardReceiveCodeRecord, Integer> BATCH_ID = createField("batch_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "批次ID");

    /**
     * The column <code>mini_shop_471752.b2c_card_receive_code.group_id</code>. 分组ID
     */
    public final TableField<B2cCardReceiveCodeRecord, Integer> GROUP_ID = createField("group_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGER)), this, "分组ID");

    /**
     * The column <code>mini_shop_471752.b2c_card_receive_code.code</code>. 领取码
     */
    public final TableField<B2cCardReceiveCodeRecord, String> CODE = createField("code", org.jooq.impl.SQLDataType.VARCHAR(15), this, "领取码");

    /**
     * The column <code>mini_shop_471752.b2c_card_receive_code.card_no</code>. 卡号
     */
    public final TableField<B2cCardReceiveCodeRecord, String> CARD_NO = createField("card_no", org.jooq.impl.SQLDataType.VARCHAR(30), this, "卡号");

    /**
     * The column <code>mini_shop_471752.b2c_card_receive_code.card_pwd</code>. 卡密码
     */
    public final TableField<B2cCardReceiveCodeRecord, String> CARD_PWD = createField("card_pwd", org.jooq.impl.SQLDataType.VARCHAR(20), this, "卡密码");

    /**
     * The column <code>mini_shop_471752.b2c_card_receive_code.user_id</code>. 领取人
     */
    public final TableField<B2cCardReceiveCodeRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "领取人");

    /**
     * The column <code>mini_shop_471752.b2c_card_receive_code.receive_time</code>. 领取时间
     */
    public final TableField<B2cCardReceiveCodeRecord, Timestamp> RECEIVE_TIME = createField("receive_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "领取时间");

    /**
     * The column <code>mini_shop_471752.b2c_card_receive_code.error_msg</code>. 错误说明
     */
    public final TableField<B2cCardReceiveCodeRecord, String> ERROR_MSG = createField("error_msg", org.jooq.impl.SQLDataType.VARCHAR(200), this, "错误说明");

    /**
     * The column <code>mini_shop_471752.b2c_card_receive_code.add_time</code>.
     */
    public final TableField<B2cCardReceiveCodeRecord, Timestamp> ADD_TIME = createField("add_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>mini_shop_471752.b2c_card_receive_code.update_time</code>.
     */
    public final TableField<B2cCardReceiveCodeRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>mini_shop_471752.b2c_card_receive_code.del_flag</code>.
     */
    public final TableField<B2cCardReceiveCodeRecord, Byte> DEL_FLAG = createField("del_flag", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "");

    /**
     * The column <code>mini_shop_471752.b2c_card_receive_code.del_time</code>.
     */
    public final TableField<B2cCardReceiveCodeRecord, Timestamp> DEL_TIME = createField("del_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>mini_shop_471752.b2c_card_receive_code</code> table reference
     */
    public B2cCardReceiveCode() {
        this(DSL.name("b2c_card_receive_code"), null);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_card_receive_code</code> table reference
     */
    public B2cCardReceiveCode(String alias) {
        this(DSL.name(alias), B2C_CARD_RECEIVE_CODE);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_card_receive_code</code> table reference
     */
    public B2cCardReceiveCode(Name alias) {
        this(alias, B2C_CARD_RECEIVE_CODE);
    }

    private B2cCardReceiveCode(Name alias, Table<B2cCardReceiveCodeRecord> aliased) {
        this(alias, aliased, null);
    }

    private B2cCardReceiveCode(Name alias, Table<B2cCardReceiveCodeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> B2cCardReceiveCode(Table<O> child, ForeignKey<O, B2cCardReceiveCodeRecord> key) {
        super(child, key, B2C_CARD_RECEIVE_CODE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MiniShop_471752.MINI_SHOP_471752;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.B2C_CARD_RECEIVE_CODE_BATCH_ID, Indexes.B2C_CARD_RECEIVE_CODE_CARD_ID, Indexes.B2C_CARD_RECEIVE_CODE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<B2cCardReceiveCodeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_B2C_CARD_RECEIVE_CODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<B2cCardReceiveCodeRecord> getPrimaryKey() {
        return Keys.KEY_B2C_CARD_RECEIVE_CODE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<B2cCardReceiveCodeRecord>> getKeys() {
        return Arrays.<UniqueKey<B2cCardReceiveCodeRecord>>asList(Keys.KEY_B2C_CARD_RECEIVE_CODE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cCardReceiveCode as(String alias) {
        return new B2cCardReceiveCode(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cCardReceiveCode as(Name alias) {
        return new B2cCardReceiveCode(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cCardReceiveCode rename(String name) {
        return new B2cCardReceiveCode(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cCardReceiveCode rename(Name name) {
        return new B2cCardReceiveCode(name, null);
    }
}
