/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables;


import com.vpu.mp.db.shop.Indexes;
import com.vpu.mp.db.shop.Keys;
import com.vpu.mp.db.shop.MiniShop_471752;
import com.vpu.mp.db.shop.tables.records.B2cChargeMoneyRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cChargeMoney extends TableImpl<B2cChargeMoneyRecord> {

    private static final long serialVersionUID = -955792141;

    /**
     * The reference instance of <code>mini_shop_471752.b2c_charge_money</code>
     */
    public static final B2cChargeMoney B2C_CHARGE_MONEY = new B2cChargeMoney();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<B2cChargeMoneyRecord> getRecordType() {
        return B2cChargeMoneyRecord.class;
    }

    /**
     * The column <code>mini_shop_471752.b2c_charge_money.id</code>.
     */
    public final TableField<B2cChargeMoneyRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>mini_shop_471752.b2c_charge_money.user_id</code>. 用户id
     */
    public final TableField<B2cChargeMoneyRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "用户id");

    /**
     * The column <code>mini_shop_471752.b2c_charge_money.card_id</code>. 会员卡id
     */
    public final TableField<B2cChargeMoneyRecord, Integer> CARD_ID = createField("card_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "会员卡id");

    /**
     * The column <code>mini_shop_471752.b2c_charge_money.add_time</code>. 充值时间
     */
    public final TableField<B2cChargeMoneyRecord, Timestamp> ADD_TIME = createField("add_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "充值时间");

    /**
     * The column <code>mini_shop_471752.b2c_charge_money.charge</code>. 充值的钱
     */
    public final TableField<B2cChargeMoneyRecord, BigDecimal> CHARGE = createField("charge", org.jooq.impl.SQLDataType.DECIMAL(10, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "充值的钱");

    /**
     * The column <code>mini_shop_471752.b2c_charge_money.count</code>. 充值次数
     */
    public final TableField<B2cChargeMoneyRecord, Short> COUNT = createField("count", org.jooq.impl.SQLDataType.SMALLINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.SMALLINT)), this, "充值次数");

    /**
     * The column <code>mini_shop_471752.b2c_charge_money.payment</code>. 支付方式
     */
    public final TableField<B2cChargeMoneyRecord, String> PAYMENT = createField("payment", org.jooq.impl.SQLDataType.VARCHAR(90).nullable(false), this, "支付方式");

    /**
     * The column <code>mini_shop_471752.b2c_charge_money.type</code>. 消费类型 0是普通卡 1限次卡
     */
    public final TableField<B2cChargeMoneyRecord, Byte> TYPE = createField("type", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "消费类型 0是普通卡 1限次卡");

    /**
     * The column <code>mini_shop_471752.b2c_charge_money.reason</code>. 充值原因
     */
    public final TableField<B2cChargeMoneyRecord, String> REASON = createField("reason", org.jooq.impl.SQLDataType.VARCHAR(191), this, "充值原因");

    /**
     * The column <code>mini_shop_471752.b2c_charge_money.prepay_id</code>. 微信支付Id，用于发送模板消息
     */
    public final TableField<B2cChargeMoneyRecord, String> PREPAY_ID = createField("prepay_id", org.jooq.impl.SQLDataType.VARCHAR(191), this, "微信支付Id，用于发送模板消息");

    /**
     * The column <code>mini_shop_471752.b2c_charge_money.message</code>. 备注
     */
    public final TableField<B2cChargeMoneyRecord, String> MESSAGE = createField("message", org.jooq.impl.SQLDataType.VARCHAR(191).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "备注");

    /**
     * The column <code>mini_shop_471752.b2c_charge_money.order_sn</code>.
     */
    public final TableField<B2cChargeMoneyRecord, String> ORDER_SN = createField("order_sn", org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mini_shop_471752.b2c_charge_money.order_status</code>. 订单状态 0：待支付，1：已取消，2：已完成
     */
    public final TableField<B2cChargeMoneyRecord, Byte> ORDER_STATUS = createField("order_status", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "订单状态 0：待支付，1：已取消，2：已完成");

    /**
     * The column <code>mini_shop_471752.b2c_charge_money.money_paid</code>. 订单应付金额
     */
    public final TableField<B2cChargeMoneyRecord, BigDecimal> MONEY_PAID = createField("money_paid", org.jooq.impl.SQLDataType.DECIMAL(10, 2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "订单应付金额");

    /**
     * The column <code>mini_shop_471752.b2c_charge_money.charge_type</code>. 0按规则 1自定义
     */
    public final TableField<B2cChargeMoneyRecord, Byte> CHARGE_TYPE = createField("charge_type", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "0按规则 1自定义");

    /**
     * The column <code>mini_shop_471752.b2c_charge_money.card_no</code>. 会员卡号
     */
    public final TableField<B2cChargeMoneyRecord, String> CARD_NO = createField("card_no", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "会员卡号");

    /**
     * The column <code>mini_shop_471752.b2c_charge_money.ali_trade_no</code>. 支付宝交易单号
     */
    public final TableField<B2cChargeMoneyRecord, String> ALI_TRADE_NO = createField("ali_trade_no", org.jooq.impl.SQLDataType.VARCHAR(60).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "支付宝交易单号");

    /**
     * The column <code>mini_shop_471752.b2c_charge_money.exchang_count</code>. 兑换充值次数
     */
    public final TableField<B2cChargeMoneyRecord, Short> EXCHANG_COUNT = createField("exchang_count", org.jooq.impl.SQLDataType.SMALLINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.SMALLINT)), this, "兑换充值次数");

    /**
     * Create a <code>mini_shop_471752.b2c_charge_money</code> table reference
     */
    public B2cChargeMoney() {
        this(DSL.name("b2c_charge_money"), null);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_charge_money</code> table reference
     */
    public B2cChargeMoney(String alias) {
        this(DSL.name(alias), B2C_CHARGE_MONEY);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_charge_money</code> table reference
     */
    public B2cChargeMoney(Name alias) {
        this(alias, B2C_CHARGE_MONEY);
    }

    private B2cChargeMoney(Name alias, Table<B2cChargeMoneyRecord> aliased) {
        this(alias, aliased, null);
    }

    private B2cChargeMoney(Name alias, Table<B2cChargeMoneyRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> B2cChargeMoney(Table<O> child, ForeignKey<O, B2cChargeMoneyRecord> key) {
        super(child, key, B2C_CHARGE_MONEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MiniShop_471752.MINI_SHOP_471752;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.B2C_CHARGE_MONEY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<B2cChargeMoneyRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_B2C_CHARGE_MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<B2cChargeMoneyRecord> getPrimaryKey() {
        return Keys.KEY_B2C_CHARGE_MONEY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<B2cChargeMoneyRecord>> getKeys() {
        return Arrays.<UniqueKey<B2cChargeMoneyRecord>>asList(Keys.KEY_B2C_CHARGE_MONEY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cChargeMoney as(String alias) {
        return new B2cChargeMoney(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cChargeMoney as(Name alias) {
        return new B2cChargeMoney(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cChargeMoney rename(String name) {
        return new B2cChargeMoney(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cChargeMoney rename(Name name) {
        return new B2cChargeMoney(name, null);
    }
}
