/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables;


import com.vpu.mp.db.shop.Indexes;
import com.vpu.mp.db.shop.Keys;
import com.vpu.mp.db.shop.MiniShop_471752;
import com.vpu.mp.db.shop.tables.records.B2cFriendPromoteTimesRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cFriendPromoteTimes extends TableImpl<B2cFriendPromoteTimesRecord> {

    private static final long serialVersionUID = 785259470;

    /**
     * The reference instance of <code>mini_shop_471752.b2c_friend_promote_times</code>
     */
    public static final B2cFriendPromoteTimes B2C_FRIEND_PROMOTE_TIMES = new B2cFriendPromoteTimes();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<B2cFriendPromoteTimesRecord> getRecordType() {
        return B2cFriendPromoteTimesRecord.class;
    }

    /**
     * The column <code>mini_shop_471752.b2c_friend_promote_times.id</code>.
     */
    public final TableField<B2cFriendPromoteTimesRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>mini_shop_471752.b2c_friend_promote_times.launch_id</code>. 助力活动发起ID
     */
    public final TableField<B2cFriendPromoteTimesRecord, Integer> LAUNCH_ID = createField("launch_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "助力活动发起ID");

    /**
     * The column <code>mini_shop_471752.b2c_friend_promote_times.user_id</code>. 助力会员ID
     */
    public final TableField<B2cFriendPromoteTimesRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "助力会员ID");

    /**
     * The column <code>mini_shop_471752.b2c_friend_promote_times.share_times</code>. 分享的次数
     */
    public final TableField<B2cFriendPromoteTimesRecord, Integer> SHARE_TIMES = createField("share_times", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "分享的次数");

    /**
     * The column <code>mini_shop_471752.b2c_friend_promote_times.own_promote_times</code>. 总的所有助力次数
     */
    public final TableField<B2cFriendPromoteTimesRecord, Integer> OWN_PROMOTE_TIMES = createField("own_promote_times", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "总的所有助力次数");

    /**
     * The column <code>mini_shop_471752.b2c_friend_promote_times.in_time</code>. 助力时间
     */
    public final TableField<B2cFriendPromoteTimesRecord, Timestamp> IN_TIME = createField("in_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "助力时间");

    /**
     * The column <code>mini_shop_471752.b2c_friend_promote_times.up_time</code>. 更新时间
     */
    public final TableField<B2cFriendPromoteTimesRecord, Timestamp> UP_TIME = createField("up_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "更新时间");

    /**
     * The column <code>mini_shop_471752.b2c_friend_promote_times.is_auth</code>. 是否有授权增加次数：0没有，1有
     */
    public final TableField<B2cFriendPromoteTimesRecord, Byte> IS_AUTH = createField("is_auth", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "是否有授权增加次数：0没有，1有");

    /**
     * Create a <code>mini_shop_471752.b2c_friend_promote_times</code> table reference
     */
    public B2cFriendPromoteTimes() {
        this(DSL.name("b2c_friend_promote_times"), null);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_friend_promote_times</code> table reference
     */
    public B2cFriendPromoteTimes(String alias) {
        this(DSL.name(alias), B2C_FRIEND_PROMOTE_TIMES);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_friend_promote_times</code> table reference
     */
    public B2cFriendPromoteTimes(Name alias) {
        this(alias, B2C_FRIEND_PROMOTE_TIMES);
    }

    private B2cFriendPromoteTimes(Name alias, Table<B2cFriendPromoteTimesRecord> aliased) {
        this(alias, aliased, null);
    }

    private B2cFriendPromoteTimes(Name alias, Table<B2cFriendPromoteTimesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> B2cFriendPromoteTimes(Table<O> child, ForeignKey<O, B2cFriendPromoteTimesRecord> key) {
        super(child, key, B2C_FRIEND_PROMOTE_TIMES);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MiniShop_471752.MINI_SHOP_471752;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.B2C_FRIEND_PROMOTE_TIMES_LAUNCH_ID, Indexes.B2C_FRIEND_PROMOTE_TIMES_PRIMARY, Indexes.B2C_FRIEND_PROMOTE_TIMES_USER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<B2cFriendPromoteTimesRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_B2C_FRIEND_PROMOTE_TIMES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<B2cFriendPromoteTimesRecord> getPrimaryKey() {
        return Keys.KEY_B2C_FRIEND_PROMOTE_TIMES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<B2cFriendPromoteTimesRecord>> getKeys() {
        return Arrays.<UniqueKey<B2cFriendPromoteTimesRecord>>asList(Keys.KEY_B2C_FRIEND_PROMOTE_TIMES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cFriendPromoteTimes as(String alias) {
        return new B2cFriendPromoteTimes(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cFriendPromoteTimes as(Name alias) {
        return new B2cFriendPromoteTimes(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cFriendPromoteTimes rename(String name) {
        return new B2cFriendPromoteTimes(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cFriendPromoteTimes rename(Name name) {
        return new B2cFriendPromoteTimes(name, null);
    }
}
