/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables;


import com.vpu.mp.db.shop.Indexes;
import com.vpu.mp.db.shop.Keys;
import com.vpu.mp.db.shop.MiniShop_471752;
import com.vpu.mp.db.shop.tables.records.B2cIncomeOutcomeDetailRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cIncomeOutcomeDetail extends TableImpl<B2cIncomeOutcomeDetailRecord> {

    private static final long serialVersionUID = -1508277014;

    /**
     * The reference instance of <code>mini_shop_471752.b2c_income_outcome_detail</code>
     */
    public static final B2cIncomeOutcomeDetail B2C_INCOME_OUTCOME_DETAIL = new B2cIncomeOutcomeDetail();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<B2cIncomeOutcomeDetailRecord> getRecordType() {
        return B2cIncomeOutcomeDetailRecord.class;
    }

    /**
     * The column <code>mini_shop_471752.b2c_income_outcome_detail.id</code>.
     */
    public final TableField<B2cIncomeOutcomeDetailRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>mini_shop_471752.b2c_income_outcome_detail.req_id</code>.
     */
    public final TableField<B2cIncomeOutcomeDetailRecord, Integer> REQ_ID = createField("req_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>mini_shop_471752.b2c_income_outcome_detail.shop_id</code>. 店铺ID
     */
    public final TableField<B2cIncomeOutcomeDetailRecord, Integer> SHOP_ID = createField("shop_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "店铺ID");

    /**
     * The column <code>mini_shop_471752.b2c_income_outcome_detail.pay_sn</code>. 支付流水号
     */
    public final TableField<B2cIncomeOutcomeDetailRecord, String> PAY_SN = createField("pay_sn", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "支付流水号");

    /**
     * The column <code>mini_shop_471752.b2c_income_outcome_detail.pay_code</code>. 支付宝:alipay,微信：？，...
     */
    public final TableField<B2cIncomeOutcomeDetailRecord, String> PAY_CODE = createField("pay_code", org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "支付宝:alipay,微信：？，...");

    /**
     * The column <code>mini_shop_471752.b2c_income_outcome_detail.pay_code_alias</code>. 支付宝:alipay,微信：？，...
     */
    public final TableField<B2cIncomeOutcomeDetailRecord, String> PAY_CODE_ALIAS = createField("pay_code_alias", org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "支付宝:alipay,微信：？，...");

    /**
     * The column <code>mini_shop_471752.b2c_income_outcome_detail.pay_act_name</code>. 支付说明
     */
    public final TableField<B2cIncomeOutcomeDetailRecord, String> PAY_ACT_NAME = createField("pay_act_name", org.jooq.impl.SQLDataType.VARCHAR(120).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "支付说明");

    /**
     * The column <code>mini_shop_471752.b2c_income_outcome_detail.pay_act_time</code>. 交易付款时间
     */
    public final TableField<B2cIncomeOutcomeDetailRecord, Timestamp> PAY_ACT_TIME = createField("pay_act_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "交易付款时间");

    /**
     * The column <code>mini_shop_471752.b2c_income_outcome_detail.income_amount</code>. 收入金额
     */
    public final TableField<B2cIncomeOutcomeDetailRecord, BigDecimal> INCOME_AMOUNT = createField("income_amount", org.jooq.impl.SQLDataType.DECIMAL(15, 2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "收入金额");

    /**
     * The column <code>mini_shop_471752.b2c_income_outcome_detail.outcome_amount</code>. 支出金额
     */
    public final TableField<B2cIncomeOutcomeDetailRecord, BigDecimal> OUTCOME_AMOUNT = createField("outcome_amount", org.jooq.impl.SQLDataType.DECIMAL(15, 2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "支出金额");

    /**
     * The column <code>mini_shop_471752.b2c_income_outcome_detail.pay_fee</code>. 手续费
     */
    public final TableField<B2cIncomeOutcomeDetailRecord, BigDecimal> PAY_FEE = createField("pay_fee", org.jooq.impl.SQLDataType.DECIMAL(15, 2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "手续费");

    /**
     * The column <code>mini_shop_471752.b2c_income_outcome_detail.total_surplus_amount</code>. 余额
     */
    public final TableField<B2cIncomeOutcomeDetailRecord, BigDecimal> TOTAL_SURPLUS_AMOUNT = createField("total_surplus_amount", org.jooq.impl.SQLDataType.DECIMAL(20, 2).nullable(false).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "余额");

    /**
     * The column <code>mini_shop_471752.b2c_income_outcome_detail.trade_no</code>. 各平台交易号
     */
    public final TableField<B2cIncomeOutcomeDetailRecord, String> TRADE_NO = createField("trade_no", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "各平台交易号");

    /**
     * The column <code>mini_shop_471752.b2c_income_outcome_detail.order_sn</code>. 网站订单号
     */
    public final TableField<B2cIncomeOutcomeDetailRecord, String> ORDER_SN = createField("order_sn", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "网站订单号");

    /**
     * The column <code>mini_shop_471752.b2c_income_outcome_detail.order_comp_status</code>. 订单完成状态1：已完成，2:未完成
     */
    public final TableField<B2cIncomeOutcomeDetailRecord, UByte> ORDER_COMP_STATUS = createField("order_comp_status", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINTUNSIGNED)), this, "订单完成状态1：已完成，2:未完成");

    /**
     * The column <code>mini_shop_471752.b2c_income_outcome_detail.update_order_status_time</code>. 更新订单状态时间
     */
    public final TableField<B2cIncomeOutcomeDetailRecord, Timestamp> UPDATE_ORDER_STATUS_TIME = createField("update_order_status_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "更新订单状态时间");

    /**
     * The column <code>mini_shop_471752.b2c_income_outcome_detail.pay_type</code>. 支付类型 1:收入，2：支出
     */
    public final TableField<B2cIncomeOutcomeDetailRecord, Byte> PAY_TYPE = createField("pay_type", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "支付类型 1:收入，2：支出");

    /**
     * The column <code>mini_shop_471752.b2c_income_outcome_detail.pay_type_name</code>. 支付类型名称
     */
    public final TableField<B2cIncomeOutcomeDetailRecord, String> PAY_TYPE_NAME = createField("pay_type_name", org.jooq.impl.SQLDataType.VARCHAR(32).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "支付类型名称");

    /**
     * The column <code>mini_shop_471752.b2c_income_outcome_detail.remark</code>. 自定义备注
     */
    public final TableField<B2cIncomeOutcomeDetailRecord, String> REMARK = createField("remark", org.jooq.impl.SQLDataType.CLOB, this, "自定义备注");

    /**
     * The column <code>mini_shop_471752.b2c_income_outcome_detail.created</code>. 创建时间
     */
    public final TableField<B2cIncomeOutcomeDetailRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "创建时间");

    /**
     * The column <code>mini_shop_471752.b2c_income_outcome_detail.no_settle_flag</code>. 是否参与结算 0:参入，1：不参与
     */
    public final TableField<B2cIncomeOutcomeDetailRecord, Byte> NO_SETTLE_FLAG = createField("no_settle_flag", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "是否参与结算 0:参入，1：不参与");

    /**
     * Create a <code>mini_shop_471752.b2c_income_outcome_detail</code> table reference
     */
    public B2cIncomeOutcomeDetail() {
        this(DSL.name("b2c_income_outcome_detail"), null);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_income_outcome_detail</code> table reference
     */
    public B2cIncomeOutcomeDetail(String alias) {
        this(DSL.name(alias), B2C_INCOME_OUTCOME_DETAIL);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_income_outcome_detail</code> table reference
     */
    public B2cIncomeOutcomeDetail(Name alias) {
        this(alias, B2C_INCOME_OUTCOME_DETAIL);
    }

    private B2cIncomeOutcomeDetail(Name alias, Table<B2cIncomeOutcomeDetailRecord> aliased) {
        this(alias, aliased, null);
    }

    private B2cIncomeOutcomeDetail(Name alias, Table<B2cIncomeOutcomeDetailRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> B2cIncomeOutcomeDetail(Table<O> child, ForeignKey<O, B2cIncomeOutcomeDetailRecord> key) {
        super(child, key, B2C_INCOME_OUTCOME_DETAIL);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MiniShop_471752.MINI_SHOP_471752;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.B2C_INCOME_OUTCOME_DETAIL_ORDER_SN, Indexes.B2C_INCOME_OUTCOME_DETAIL_PAY_CODE, Indexes.B2C_INCOME_OUTCOME_DETAIL_PAY_SN, Indexes.B2C_INCOME_OUTCOME_DETAIL_PAY_TYPE, Indexes.B2C_INCOME_OUTCOME_DETAIL_PRIMARY, Indexes.B2C_INCOME_OUTCOME_DETAIL_SHOP_ID, Indexes.B2C_INCOME_OUTCOME_DETAIL_TRADE_NO);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<B2cIncomeOutcomeDetailRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_B2C_INCOME_OUTCOME_DETAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<B2cIncomeOutcomeDetailRecord> getPrimaryKey() {
        return Keys.KEY_B2C_INCOME_OUTCOME_DETAIL_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<B2cIncomeOutcomeDetailRecord>> getKeys() {
        return Arrays.<UniqueKey<B2cIncomeOutcomeDetailRecord>>asList(Keys.KEY_B2C_INCOME_OUTCOME_DETAIL_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cIncomeOutcomeDetail as(String alias) {
        return new B2cIncomeOutcomeDetail(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cIncomeOutcomeDetail as(Name alias) {
        return new B2cIncomeOutcomeDetail(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cIncomeOutcomeDetail rename(String name) {
        return new B2cIncomeOutcomeDetail(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cIncomeOutcomeDetail rename(Name name) {
        return new B2cIncomeOutcomeDetail(name, null);
    }
}
