/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables;


import com.vpu.mp.db.shop.Indexes;
import com.vpu.mp.db.shop.Keys;
import com.vpu.mp.db.shop.MiniShop_471752;
import com.vpu.mp.db.shop.tables.records.B2cIntegralMallRecordRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cIntegralMallRecord extends TableImpl<B2cIntegralMallRecordRecord> {

    private static final long serialVersionUID = -1093049981;

    /**
     * The reference instance of <code>mini_shop_471752.b2c_integral_mall_record</code>
     */
    public static final B2cIntegralMallRecord B2C_INTEGRAL_MALL_RECORD = new B2cIntegralMallRecord();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<B2cIntegralMallRecordRecord> getRecordType() {
        return B2cIntegralMallRecordRecord.class;
    }

    /**
     * The column <code>mini_shop_471752.b2c_integral_mall_record.id</code>.
     */
    public final TableField<B2cIntegralMallRecordRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>mini_shop_471752.b2c_integral_mall_record.integral_mall_define_id</code>. 积分商城活动定义表ID
     */
    public final TableField<B2cIntegralMallRecordRecord, Integer> INTEGRAL_MALL_DEFINE_ID = createField("integral_mall_define_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "积分商城活动定义表ID");

    /**
     * The column <code>mini_shop_471752.b2c_integral_mall_record.order_sn</code>. 订单编号
     */
    public final TableField<B2cIntegralMallRecordRecord, String> ORDER_SN = createField("order_sn", org.jooq.impl.SQLDataType.VARCHAR(20), this, "订单编号");

    /**
     * The column <code>mini_shop_471752.b2c_integral_mall_record.user_id</code>. 用户ID
     */
    public final TableField<B2cIntegralMallRecordRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "用户ID");

    /**
     * The column <code>mini_shop_471752.b2c_integral_mall_record.goods_id</code>. 商品ID
     */
    public final TableField<B2cIntegralMallRecordRecord, Integer> GOODS_ID = createField("goods_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "商品ID");

    /**
     * The column <code>mini_shop_471752.b2c_integral_mall_record.product_id</code>. 产品规格ID
     */
    public final TableField<B2cIntegralMallRecordRecord, Integer> PRODUCT_ID = createField("product_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "产品规格ID");

    /**
     * The column <code>mini_shop_471752.b2c_integral_mall_record.score</code>. 消费积分
     */
    public final TableField<B2cIntegralMallRecordRecord, Integer> SCORE = createField("score", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "消费积分");

    /**
     * The column <code>mini_shop_471752.b2c_integral_mall_record.number</code>. 兑换数量
     */
    public final TableField<B2cIntegralMallRecordRecord, Short> NUMBER = createField("number", org.jooq.impl.SQLDataType.SMALLINT.nullable(false), this, "兑换数量");

    /**
     * The column <code>mini_shop_471752.b2c_integral_mall_record.add_time</code>. 兑换时间
     */
    public final TableField<B2cIntegralMallRecordRecord, Timestamp> ADD_TIME = createField("add_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "兑换时间");

    /**
     * The column <code>mini_shop_471752.b2c_integral_mall_record.money</code>. 消耗现金
     */
    public final TableField<B2cIntegralMallRecordRecord, BigDecimal> MONEY = createField("money", org.jooq.impl.SQLDataType.DECIMAL(10, 2).nullable(false), this, "消耗现金");

    /**
     * Create a <code>mini_shop_471752.b2c_integral_mall_record</code> table reference
     */
    public B2cIntegralMallRecord() {
        this(DSL.name("b2c_integral_mall_record"), null);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_integral_mall_record</code> table reference
     */
    public B2cIntegralMallRecord(String alias) {
        this(DSL.name(alias), B2C_INTEGRAL_MALL_RECORD);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_integral_mall_record</code> table reference
     */
    public B2cIntegralMallRecord(Name alias) {
        this(alias, B2C_INTEGRAL_MALL_RECORD);
    }

    private B2cIntegralMallRecord(Name alias, Table<B2cIntegralMallRecordRecord> aliased) {
        this(alias, aliased, null);
    }

    private B2cIntegralMallRecord(Name alias, Table<B2cIntegralMallRecordRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> B2cIntegralMallRecord(Table<O> child, ForeignKey<O, B2cIntegralMallRecordRecord> key) {
        super(child, key, B2C_INTEGRAL_MALL_RECORD);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MiniShop_471752.MINI_SHOP_471752;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.B2C_INTEGRAL_MALL_RECORD_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<B2cIntegralMallRecordRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_B2C_INTEGRAL_MALL_RECORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<B2cIntegralMallRecordRecord> getPrimaryKey() {
        return Keys.KEY_B2C_INTEGRAL_MALL_RECORD_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<B2cIntegralMallRecordRecord>> getKeys() {
        return Arrays.<UniqueKey<B2cIntegralMallRecordRecord>>asList(Keys.KEY_B2C_INTEGRAL_MALL_RECORD_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cIntegralMallRecord as(String alias) {
        return new B2cIntegralMallRecord(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cIntegralMallRecord as(Name alias) {
        return new B2cIntegralMallRecord(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cIntegralMallRecord rename(String name) {
        return new B2cIntegralMallRecord(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cIntegralMallRecord rename(Name name) {
        return new B2cIntegralMallRecord(name, null);
    }
}
