/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables;


import com.vpu.mp.db.shop.Indexes;
import com.vpu.mp.db.shop.Keys;
import com.vpu.mp.db.shop.MiniShop_471752;
import com.vpu.mp.db.shop.tables.records.B2cShopCfgRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;
import org.jooq.types.UShort;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cShopCfg extends TableImpl<B2cShopCfgRecord> {

    private static final long serialVersionUID = 1259626873;

    /**
     * The reference instance of <code>mini_shop_471752.b2c_shop_cfg</code>
     */
    public static final B2cShopCfg B2C_SHOP_CFG = new B2cShopCfg();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<B2cShopCfgRecord> getRecordType() {
        return B2cShopCfgRecord.class;
    }

    /**
     * The column <code>mini_shop_471752.b2c_shop_cfg.rec_id</code>.
     */
    public final TableField<B2cShopCfgRecord, UShort> REC_ID = createField("rec_id", org.jooq.impl.SQLDataType.SMALLINTUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>mini_shop_471752.b2c_shop_cfg.shop_id</code>. 店铺id
     */
    public final TableField<B2cShopCfgRecord, UInteger> SHOP_ID = createField("shop_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "店铺id");

    /**
     * The column <code>mini_shop_471752.b2c_shop_cfg.k</code>.
     */
    public final TableField<B2cShopCfgRecord, String> K = createField("k", org.jooq.impl.SQLDataType.VARCHAR(191).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mini_shop_471752.b2c_shop_cfg.v</code>.
     */
    public final TableField<B2cShopCfgRecord, String> V = createField("v", org.jooq.impl.SQLDataType.CLOB, this, "");

    /**
     * Create a <code>mini_shop_471752.b2c_shop_cfg</code> table reference
     */
    public B2cShopCfg() {
        this(DSL.name("b2c_shop_cfg"), null);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_shop_cfg</code> table reference
     */
    public B2cShopCfg(String alias) {
        this(DSL.name(alias), B2C_SHOP_CFG);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_shop_cfg</code> table reference
     */
    public B2cShopCfg(Name alias) {
        this(alias, B2C_SHOP_CFG);
    }

    private B2cShopCfg(Name alias, Table<B2cShopCfgRecord> aliased) {
        this(alias, aliased, null);
    }

    private B2cShopCfg(Name alias, Table<B2cShopCfgRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> B2cShopCfg(Table<O> child, ForeignKey<O, B2cShopCfgRecord> key) {
        super(child, key, B2C_SHOP_CFG);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MiniShop_471752.MINI_SHOP_471752;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.B2C_SHOP_CFG_PRIMARY, Indexes.B2C_SHOP_CFG_SHOP_ID_K);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<B2cShopCfgRecord, UShort> getIdentity() {
        return Keys.IDENTITY_B2C_SHOP_CFG;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<B2cShopCfgRecord> getPrimaryKey() {
        return Keys.KEY_B2C_SHOP_CFG_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<B2cShopCfgRecord>> getKeys() {
        return Arrays.<UniqueKey<B2cShopCfgRecord>>asList(Keys.KEY_B2C_SHOP_CFG_PRIMARY, Keys.KEY_B2C_SHOP_CFG_SHOP_ID_K);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cShopCfg as(String alias) {
        return new B2cShopCfg(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cShopCfg as(Name alias) {
        return new B2cShopCfg(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cShopCfg rename(String name) {
        return new B2cShopCfg(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cShopCfg rename(Name name) {
        return new B2cShopCfg(name, null);
    }
}
