/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables;


import com.vpu.mp.db.shop.Indexes;
import com.vpu.mp.db.shop.Keys;
import com.vpu.mp.db.shop.MiniShop_471752;
import com.vpu.mp.db.shop.tables.records.B2cWxShoppingRecommendRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cWxShoppingRecommend extends TableImpl<B2cWxShoppingRecommendRecord> {

    private static final long serialVersionUID = 506609859;

    /**
     * The reference instance of <code>mini_shop_471752.b2c_wx_shopping_recommend</code>
     */
    public static final B2cWxShoppingRecommend B2C_WX_SHOPPING_RECOMMEND = new B2cWxShoppingRecommend();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<B2cWxShoppingRecommendRecord> getRecordType() {
        return B2cWxShoppingRecommendRecord.class;
    }

    /**
     * The column <code>mini_shop_471752.b2c_wx_shopping_recommend.id</code>.
     */
    public final TableField<B2cWxShoppingRecommendRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>mini_shop_471752.b2c_wx_shopping_recommend.user_id</code>.
     */
    public final TableField<B2cWxShoppingRecommendRecord, Integer> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mini_shop_471752.b2c_wx_shopping_recommend.goods_id</code>. 商品ID
     */
    public final TableField<B2cWxShoppingRecommendRecord, Integer> GOODS_ID = createField("goods_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "商品ID");

    /**
     * The column <code>mini_shop_471752.b2c_wx_shopping_recommend.order_sn</code>. 订单orderSn
     */
    public final TableField<B2cWxShoppingRecommendRecord, Integer> ORDER_SN = createField("order_sn", org.jooq.impl.SQLDataType.INTEGER, this, "订单orderSn");

    /**
     * The column <code>mini_shop_471752.b2c_wx_shopping_recommend.click_num</code>. 点击次数
     */
    public final TableField<B2cWxShoppingRecommendRecord, Integer> CLICK_NUM = createField("click_num", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.INTEGER)), this, "点击次数");

    /**
     * The column <code>mini_shop_471752.b2c_wx_shopping_recommend.add_time</code>.
     */
    public final TableField<B2cWxShoppingRecommendRecord, Timestamp> ADD_TIME = createField("add_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>mini_shop_471752.b2c_wx_shopping_recommend</code> table reference
     */
    public B2cWxShoppingRecommend() {
        this(DSL.name("b2c_wx_shopping_recommend"), null);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_wx_shopping_recommend</code> table reference
     */
    public B2cWxShoppingRecommend(String alias) {
        this(DSL.name(alias), B2C_WX_SHOPPING_RECOMMEND);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_wx_shopping_recommend</code> table reference
     */
    public B2cWxShoppingRecommend(Name alias) {
        this(alias, B2C_WX_SHOPPING_RECOMMEND);
    }

    private B2cWxShoppingRecommend(Name alias, Table<B2cWxShoppingRecommendRecord> aliased) {
        this(alias, aliased, null);
    }

    private B2cWxShoppingRecommend(Name alias, Table<B2cWxShoppingRecommendRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> B2cWxShoppingRecommend(Table<O> child, ForeignKey<O, B2cWxShoppingRecommendRecord> key) {
        super(child, key, B2C_WX_SHOPPING_RECOMMEND);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MiniShop_471752.MINI_SHOP_471752;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.B2C_WX_SHOPPING_RECOMMEND_GOODS_ID, Indexes.B2C_WX_SHOPPING_RECOMMEND_PRIMARY, Indexes.B2C_WX_SHOPPING_RECOMMEND_USER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<B2cWxShoppingRecommendRecord, Integer> getIdentity() {
        return Keys.IDENTITY_B2C_WX_SHOPPING_RECOMMEND;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<B2cWxShoppingRecommendRecord> getPrimaryKey() {
        return Keys.KEY_B2C_WX_SHOPPING_RECOMMEND_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<B2cWxShoppingRecommendRecord>> getKeys() {
        return Arrays.<UniqueKey<B2cWxShoppingRecommendRecord>>asList(Keys.KEY_B2C_WX_SHOPPING_RECOMMEND_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cWxShoppingRecommend as(String alias) {
        return new B2cWxShoppingRecommend(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cWxShoppingRecommend as(Name alias) {
        return new B2cWxShoppingRecommend(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cWxShoppingRecommend rename(String name) {
        return new B2cWxShoppingRecommend(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cWxShoppingRecommend rename(Name name) {
        return new B2cWxShoppingRecommend(name, null);
    }
}
