/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables;


import com.vpu.mp.db.shop.Indexes;
import com.vpu.mp.db.shop.Keys;
import com.vpu.mp.db.shop.MiniShop_471752;
import com.vpu.mp.db.shop.tables.records.B2cWxpMessageRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cWxpMessage extends TableImpl<B2cWxpMessageRecord> {

    private static final long serialVersionUID = 558778033;

    /**
     * The reference instance of <code>mini_shop_471752.b2c_wxp_message</code>
     */
    public static final B2cWxpMessage B2C_WXP_MESSAGE = new B2cWxpMessage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<B2cWxpMessageRecord> getRecordType() {
        return B2cWxpMessageRecord.class;
    }

    /**
     * The column <code>mini_shop_471752.b2c_wxp_message.rec_id</code>.
     */
    public final TableField<B2cWxpMessageRecord, UInteger> REC_ID = createField("rec_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>mini_shop_471752.b2c_wxp_message.shop_id</code>. 店铺ID
     */
    public final TableField<B2cWxpMessageRecord, Integer> SHOP_ID = createField("shop_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "店铺ID");

    /**
     * The column <code>mini_shop_471752.b2c_wxp_message.type</code>. 消息收发类型 0：接收，1自动回复 2 客服回复
     */
    public final TableField<B2cWxpMessageRecord, Byte> TYPE = createField("type", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "消息收发类型 0：接收，1自动回复 2 客服回复");

    /**
     * The column <code>mini_shop_471752.b2c_wxp_message.customer_user</code>.
     */
    public final TableField<B2cWxpMessageRecord, String> CUSTOMER_USER = createField("customer_user", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>mini_shop_471752.b2c_wxp_message.msgtype</code>. type=0时，取值text,image,voice,video,location,link,subscribe,unsubscribe,SCAN,LOCATION,CLICK,VIEW
     */
    public final TableField<B2cWxpMessageRecord, String> MSGTYPE = createField("msgtype", org.jooq.impl.SQLDataType.VARCHAR(50), this, "type=0时，取值text,image,voice,video,location,link,subscribe,unsubscribe,SCAN,LOCATION,CLICK,VIEW");

    /**
     * The column <code>mini_shop_471752.b2c_wxp_message.content</code>. 原始发送或接收的内容，type=0 1时，是xmldata，2时是json数据
     */
    public final TableField<B2cWxpMessageRecord, String> CONTENT = createField("content", org.jooq.impl.SQLDataType.CLOB, this, "原始发送或接收的内容，type=0 1时，是xmldata，2时是json数据");

    /**
     * The column <code>mini_shop_471752.b2c_wxp_message.menu_name</code>. 菜单名称,type=0 &amp;&amp; msgtype=CLICK,VIEW有效
     */
    public final TableField<B2cWxpMessageRecord, String> MENU_NAME = createField("menu_name", org.jooq.impl.SQLDataType.VARCHAR(191).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "菜单名称,type=0 && msgtype=CLICK,VIEW有效");

    /**
     * The column <code>mini_shop_471752.b2c_wxp_message.res_cfg_type</code>. 0 关注时回复，1关键词回复，2默认回复,3菜单回复
     */
    public final TableField<B2cWxpMessageRecord, Byte> RES_CFG_TYPE = createField("res_cfg_type", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "0 关注时回复，1关键词回复，2默认回复,3菜单回复");

    /**
     * The column <code>mini_shop_471752.b2c_wxp_message.res_key_words</code>. 关键词,关键词回复有效
     */
    public final TableField<B2cWxpMessageRecord, String> RES_KEY_WORDS = createField("res_key_words", org.jooq.impl.SQLDataType.VARCHAR(191).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "关键词,关键词回复有效");

    /**
     * The column <code>mini_shop_471752.b2c_wxp_message.res_content</code>. 回复时的回复内容
     */
    public final TableField<B2cWxpMessageRecord, String> RES_CONTENT = createField("res_content", org.jooq.impl.SQLDataType.CLOB, this, "回复时的回复内容");

    /**
     * The column <code>mini_shop_471752.b2c_wxp_message.res_rec_id</code>. 素材wxp_material的rec_id
     */
    public final TableField<B2cWxpMessageRecord, Integer> RES_REC_ID = createField("res_rec_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "素材wxp_material的rec_id");

    /**
     * The column <code>mini_shop_471752.b2c_wxp_message.res_parent_rec_id</code>. 对某个用户某条消息进行回复，这个是消息对的rec_id
     */
    public final TableField<B2cWxpMessageRecord, Integer> RES_PARENT_REC_ID = createField("res_parent_rec_id", org.jooq.impl.SQLDataType.INTEGER.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "对某个用户某条消息进行回复，这个是消息对的rec_id");

    /**
     * The column <code>mini_shop_471752.b2c_wxp_message.is_responsed</code>. 对type=0有意义，当有客服消息回复了，代表已回复
     */
    public final TableField<B2cWxpMessageRecord, Byte> IS_RESPONSED = createField("is_responsed", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "对type=0有意义，当有客服消息回复了，代表已回复");

    /**
     * The column <code>mini_shop_471752.b2c_wxp_message.star_flag</code>. 是否星标收藏
     */
    public final TableField<B2cWxpMessageRecord, Byte> STAR_FLAG = createField("star_flag", org.jooq.impl.SQLDataType.TINYINT.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "是否星标收藏");

    /**
     * The column <code>mini_shop_471752.b2c_wxp_message.micro_id</code>. 所属微信公众号ID,关联b2c_wxp_list的micro_id
     */
    public final TableField<B2cWxpMessageRecord, Integer> MICRO_ID = createField("micro_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "所属微信公众号ID,关联b2c_wxp_list的micro_id");

    /**
     * The column <code>mini_shop_471752.b2c_wxp_message.create_time</code>.
     */
    public final TableField<B2cWxpMessageRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>mini_shop_471752.b2c_wxp_message</code> table reference
     */
    public B2cWxpMessage() {
        this(DSL.name("b2c_wxp_message"), null);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_wxp_message</code> table reference
     */
    public B2cWxpMessage(String alias) {
        this(DSL.name(alias), B2C_WXP_MESSAGE);
    }

    /**
     * Create an aliased <code>mini_shop_471752.b2c_wxp_message</code> table reference
     */
    public B2cWxpMessage(Name alias) {
        this(alias, B2C_WXP_MESSAGE);
    }

    private B2cWxpMessage(Name alias, Table<B2cWxpMessageRecord> aliased) {
        this(alias, aliased, null);
    }

    private B2cWxpMessage(Name alias, Table<B2cWxpMessageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> B2cWxpMessage(Table<O> child, ForeignKey<O, B2cWxpMessageRecord> key) {
        super(child, key, B2C_WXP_MESSAGE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MiniShop_471752.MINI_SHOP_471752;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.B2C_WXP_MESSAGE_MICRO_ID, Indexes.B2C_WXP_MESSAGE_PRIMARY, Indexes.B2C_WXP_MESSAGE_STAR_FLAG, Indexes.B2C_WXP_MESSAGE_TYPE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<B2cWxpMessageRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_B2C_WXP_MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<B2cWxpMessageRecord> getPrimaryKey() {
        return Keys.KEY_B2C_WXP_MESSAGE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<B2cWxpMessageRecord>> getKeys() {
        return Arrays.<UniqueKey<B2cWxpMessageRecord>>asList(Keys.KEY_B2C_WXP_MESSAGE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cWxpMessage as(String alias) {
        return new B2cWxpMessage(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cWxpMessage as(Name alias) {
        return new B2cWxpMessage(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cWxpMessage rename(String name) {
        return new B2cWxpMessage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cWxpMessage rename(Name name) {
        return new B2cWxpMessage(name, null);
    }
}
