/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables;


import com.vpu.mp.db.shop.Indexes;
import com.vpu.mp.db.shop.Keys;
import com.vpu.mp.db.shop.MiniShop_1;
import com.vpu.mp.db.shop.tables.records.ChannelRecordRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChannelRecord extends TableImpl<ChannelRecordRecord> {

    private static final long serialVersionUID = 2019349848;

    /**
     * The reference instance of <code>mini_shop_1.b2c_channel_record</code>
     */
    public static final ChannelRecord CHANNEL_RECORD = new ChannelRecord();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ChannelRecordRecord> getRecordType() {
        return ChannelRecordRecord.class;
    }

    /**
     * The column <code>mini_shop_1.b2c_channel_record.id</code>. id
     */
    public final TableField<ChannelRecordRecord, UInteger> ID = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "id");

    /**
     * The column <code>mini_shop_1.b2c_channel_record.channel_id</code>. 渠道页ID
     */
    public final TableField<ChannelRecordRecord, UInteger> CHANNEL_ID = createField("channel_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "渠道页ID");

    /**
     * The column <code>mini_shop_1.b2c_channel_record.user_id</code>. userID
     */
    public final TableField<ChannelRecordRecord, UInteger> USER_ID = createField("user_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "userID");

    /**
     * The column <code>mini_shop_1.b2c_channel_record.type</code>. 类型 1新用 0老用户
     */
    public final TableField<ChannelRecordRecord, Byte> TYPE = createField("type", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "类型 1新用 0老用户");

    /**
     * The column <code>mini_shop_1.b2c_channel_record.count</code>. 访问次数
     */
    public final TableField<ChannelRecordRecord, UInteger> COUNT = createField("count", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "访问次数");

    /**
     * The column <code>mini_shop_1.b2c_channel_record.add_time</code>.
     */
    public final TableField<ChannelRecordRecord, Timestamp> ADD_TIME = createField("add_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>mini_shop_1.b2c_channel_record</code> table reference
     */
    public ChannelRecord() {
        this(DSL.name("b2c_channel_record"), null);
    }

    /**
     * Create an aliased <code>mini_shop_1.b2c_channel_record</code> table reference
     */
    public ChannelRecord(String alias) {
        this(DSL.name(alias), CHANNEL_RECORD);
    }

    /**
     * Create an aliased <code>mini_shop_1.b2c_channel_record</code> table reference
     */
    public ChannelRecord(Name alias) {
        this(alias, CHANNEL_RECORD);
    }

    private ChannelRecord(Name alias, Table<ChannelRecordRecord> aliased) {
        this(alias, aliased, null);
    }

    private ChannelRecord(Name alias, Table<ChannelRecordRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> ChannelRecord(Table<O> child, ForeignKey<O, ChannelRecordRecord> key) {
        super(child, key, CHANNEL_RECORD);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MiniShop_1.MINI_SHOP_1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CHANNEL_RECORD_PRIMARY, Indexes.CHANNEL_RECORD_USER_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ChannelRecordRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_CHANNEL_RECORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ChannelRecordRecord> getPrimaryKey() {
        return Keys.KEY_B2C_CHANNEL_RECORD_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ChannelRecordRecord>> getKeys() {
        return Arrays.<UniqueKey<ChannelRecordRecord>>asList(Keys.KEY_B2C_CHANNEL_RECORD_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord as(String alias) {
        return new ChannelRecord(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ChannelRecord as(Name alias) {
        return new ChannelRecord(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public ChannelRecord rename(String name) {
        return new ChannelRecord(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public ChannelRecord rename(Name name) {
        return new ChannelRecord(name, null);
    }
}
