/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.main.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class App implements Serializable {

    private static final long serialVersionUID = 757830820;

    private String    appId;
    private String    appName;
    private String    appSecret;
    private Timestamp addTime;

    public App() {}

    public App(App value) {
        this.appId = value.appId;
        this.appName = value.appName;
        this.appSecret = value.appSecret;
        this.addTime = value.addTime;
    }

    public App(
        String    appId,
        String    appName,
        String    appSecret,
        Timestamp addTime
    ) {
        this.appId = appId;
        this.appName = appName;
        this.appSecret = appSecret;
        this.addTime = addTime;
    }

    public String getAppId() {
        return this.appId;
    }

    public void setAppId(String appId) {
        this.appId = appId;
    }

    public String getAppName() {
        return this.appName;
    }

    public void setAppName(String appName) {
        this.appName = appName;
    }

    public String getAppSecret() {
        return this.appSecret;
    }

    public void setAppSecret(String appSecret) {
        this.appSecret = appSecret;
    }

    public Timestamp getAddTime() {
        return this.addTime;
    }

    public void setAddTime(Timestamp addTime) {
        this.addTime = addTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("App (");

        sb.append(appId);
        sb.append(", ").append(appName);
        sb.append(", ").append(appSecret);
        sb.append(", ").append(addTime);

        sb.append(")");
        return sb.toString();
    }
}
