/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.main.tables.records;


import com.vpu.mp.db.main.tables.B2cJobs;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.UByte;
import org.jooq.types.UInteger;
import org.jooq.types.ULong;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cJobsRecord extends UpdatableRecordImpl<B2cJobsRecord> implements Record7<ULong, String, String, UByte, UInteger, UInteger, UInteger> {

    private static final long serialVersionUID = 1090596988;

    /**
     * Setter for <code>mini_main.b2c_jobs.id</code>.
     */
    public void setId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>mini_main.b2c_jobs.id</code>.
     */
    public ULong getId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>mini_main.b2c_jobs.queue</code>.
     */
    public void setQueue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mini_main.b2c_jobs.queue</code>.
     */
    public String getQueue() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mini_main.b2c_jobs.payload</code>.
     */
    public void setPayload(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>mini_main.b2c_jobs.payload</code>.
     */
    public String getPayload() {
        return (String) get(2);
    }

    /**
     * Setter for <code>mini_main.b2c_jobs.attempts</code>.
     */
    public void setAttempts(UByte value) {
        set(3, value);
    }

    /**
     * Getter for <code>mini_main.b2c_jobs.attempts</code>.
     */
    public UByte getAttempts() {
        return (UByte) get(3);
    }

    /**
     * Setter for <code>mini_main.b2c_jobs.reserved_at</code>.
     */
    public void setReservedAt(UInteger value) {
        set(4, value);
    }

    /**
     * Getter for <code>mini_main.b2c_jobs.reserved_at</code>.
     */
    public UInteger getReservedAt() {
        return (UInteger) get(4);
    }

    /**
     * Setter for <code>mini_main.b2c_jobs.available_at</code>.
     */
    public void setAvailableAt(UInteger value) {
        set(5, value);
    }

    /**
     * Getter for <code>mini_main.b2c_jobs.available_at</code>.
     */
    public UInteger getAvailableAt() {
        return (UInteger) get(5);
    }

    /**
     * Setter for <code>mini_main.b2c_jobs.created_at</code>.
     */
    public void setCreatedAt(UInteger value) {
        set(6, value);
    }

    /**
     * Getter for <code>mini_main.b2c_jobs.created_at</code>.
     */
    public UInteger getCreatedAt() {
        return (UInteger) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<ULong, String, String, UByte, UInteger, UInteger, UInteger> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<ULong, String, String, UByte, UInteger, UInteger, UInteger> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<ULong> field1() {
        return B2cJobs.B2C_JOBS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return B2cJobs.B2C_JOBS.QUEUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return B2cJobs.B2C_JOBS.PAYLOAD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UByte> field4() {
        return B2cJobs.B2C_JOBS.ATTEMPTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field5() {
        return B2cJobs.B2C_JOBS.RESERVED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field6() {
        return B2cJobs.B2C_JOBS.AVAILABLE_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UInteger> field7() {
        return B2cJobs.B2C_JOBS.CREATED_AT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getQueue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPayload();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte component4() {
        return getAttempts();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component5() {
        return getReservedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component6() {
        return getAvailableAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger component7() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ULong value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getQueue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPayload();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UByte value4() {
        return getAttempts();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value5() {
        return getReservedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value6() {
        return getAvailableAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UInteger value7() {
        return getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cJobsRecord value1(ULong value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cJobsRecord value2(String value) {
        setQueue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cJobsRecord value3(String value) {
        setPayload(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cJobsRecord value4(UByte value) {
        setAttempts(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cJobsRecord value5(UInteger value) {
        setReservedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cJobsRecord value6(UInteger value) {
        setAvailableAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cJobsRecord value7(UInteger value) {
        setCreatedAt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cJobsRecord values(ULong value1, String value2, String value3, UByte value4, UInteger value5, UInteger value6, UInteger value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached B2cJobsRecord
     */
    public B2cJobsRecord() {
        super(B2cJobs.B2C_JOBS);
    }

    /**
     * Create a detached, initialised B2cJobsRecord
     */
    public B2cJobsRecord(ULong id, String queue, String payload, UByte attempts, UInteger reservedAt, UInteger availableAt, UInteger createdAt) {
        super(B2cJobs.B2C_JOBS);

        set(0, id);
        set(1, queue);
        set(2, payload);
        set(3, attempts);
        set(4, reservedAt);
        set(5, availableAt);
        set(6, createdAt);
    }
}
