/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.main.tables.records;


import com.vpu.mp.db.main.tables.B2cMpOperateLog;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cMpOperateLogRecord extends UpdatableRecordImpl<B2cMpOperateLogRecord> implements Record6<Integer, String, Integer, Byte, String, Timestamp> {

    private static final long serialVersionUID = -393941747;

    /**
     * Setter for <code>mini_main.b2c_mp_operate_log.operate_id</code>. 自增ID
     */
    public void setOperateId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>mini_main.b2c_mp_operate_log.operate_id</code>. 自增ID
     */
    public Integer getOperateId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>mini_main.b2c_mp_operate_log.app_id</code>. 小程序app_id
     */
    public void setAppId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>mini_main.b2c_mp_operate_log.app_id</code>. 小程序app_id
     */
    public String getAppId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>mini_main.b2c_mp_operate_log.template_id</code>. 小程序模板Id
     */
    public void setTemplateId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>mini_main.b2c_mp_operate_log.template_id</code>. 小程序模板Id
     */
    public Integer getTemplateId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>mini_main.b2c_mp_operate_log.operate_type</code>. 操作类型
     */
    public void setOperateType(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>mini_main.b2c_mp_operate_log.operate_type</code>. 操作类型
     */
    public Byte getOperateType() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>mini_main.b2c_mp_operate_log.memo</code>. 操作日志
     */
    public void setMemo(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>mini_main.b2c_mp_operate_log.memo</code>. 操作日志
     */
    public String getMemo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>mini_main.b2c_mp_operate_log.create_time</code>. 记录时间
     */
    public void setCreateTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>mini_main.b2c_mp_operate_log.create_time</code>. 记录时间
     */
    public Timestamp getCreateTime() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, Byte, String, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, String, Integer, Byte, String, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return B2cMpOperateLog.B2C_MP_OPERATE_LOG.OPERATE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return B2cMpOperateLog.B2C_MP_OPERATE_LOG.APP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return B2cMpOperateLog.B2C_MP_OPERATE_LOG.TEMPLATE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return B2cMpOperateLog.B2C_MP_OPERATE_LOG.OPERATE_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return B2cMpOperateLog.B2C_MP_OPERATE_LOG.MEMO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return B2cMpOperateLog.B2C_MP_OPERATE_LOG.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getOperateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getTemplateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getOperateType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getOperateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAppId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getTemplateId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getOperateType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getMemo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpOperateLogRecord value1(Integer value) {
        setOperateId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpOperateLogRecord value2(String value) {
        setAppId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpOperateLogRecord value3(Integer value) {
        setTemplateId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpOperateLogRecord value4(Byte value) {
        setOperateType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpOperateLogRecord value5(String value) {
        setMemo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpOperateLogRecord value6(Timestamp value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpOperateLogRecord values(Integer value1, String value2, Integer value3, Byte value4, String value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached B2cMpOperateLogRecord
     */
    public B2cMpOperateLogRecord() {
        super(B2cMpOperateLog.B2C_MP_OPERATE_LOG);
    }

    /**
     * Create a detached, initialised B2cMpOperateLogRecord
     */
    public B2cMpOperateLogRecord(Integer operateId, String appId, Integer templateId, Byte operateType, String memo, Timestamp createTime) {
        super(B2cMpOperateLog.B2C_MP_OPERATE_LOG);

        set(0, operateId);
        set(1, appId);
        set(2, templateId);
        set(3, operateType);
        set(4, memo);
        set(5, createTime);
    }
}
