/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.main.tables;


import com.vpu.mp.db.main.Indexes;
import com.vpu.mp.db.main.Keys;
import com.vpu.mp.db.main.MiniMain;
import com.vpu.mp.db.main.tables.records.B2cAliMyOrderRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;
import org.jooq.types.UInteger;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cAliMyOrder extends TableImpl<B2cAliMyOrderRecord> {

    private static final long serialVersionUID = -660577069;

    /**
     * The reference instance of <code>mini_main.b2c_ali_my_order</code>
     */
    public static final B2cAliMyOrder B2C_ALI_MY_ORDER = new B2cAliMyOrder();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<B2cAliMyOrderRecord> getRecordType() {
        return B2cAliMyOrderRecord.class;
    }

    /**
     * The column <code>mini_main.b2c_ali_my_order.rec_id</code>.
     */
    public final TableField<B2cAliMyOrderRecord, UInteger> REC_ID = createField("rec_id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).identity(true), this, "");

    /**
     * The column <code>mini_main.b2c_ali_my_order.commodity_order_id</code>. 订单编号
     */
    public final TableField<B2cAliMyOrderRecord, String> COMMODITY_ORDER_ID = createField("commodity_order_id", org.jooq.impl.SQLDataType.VARCHAR(191).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "订单编号");

    /**
     * The column <code>mini_main.b2c_ali_my_order.order_time</code>. 订购时间
     */
    public final TableField<B2cAliMyOrderRecord, Timestamp> ORDER_TIME = createField("order_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "订购时间");

    /**
     * The column <code>mini_main.b2c_ali_my_order.title</code>. 服务名称
     */
    public final TableField<B2cAliMyOrderRecord, String> TITLE = createField("title", org.jooq.impl.SQLDataType.VARCHAR(191).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "服务名称");

    /**
     * The column <code>mini_main.b2c_ali_my_order.name</code>. 商户名称
     */
    public final TableField<B2cAliMyOrderRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(191).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "商户名称");

    /**
     * The column <code>mini_main.b2c_ali_my_order.merchant_pid</code>. 商户ID	
     */
    public final TableField<B2cAliMyOrderRecord, String> MERCHANT_PID = createField("merchant_pid", org.jooq.impl.SQLDataType.VARCHAR(191).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "商户ID	");

    /**
     * The column <code>mini_main.b2c_ali_my_order.contactor</code>. 联系人	
     */
    public final TableField<B2cAliMyOrderRecord, String> CONTACTOR = createField("contactor", org.jooq.impl.SQLDataType.VARCHAR(191).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "联系人	");

    /**
     * The column <code>mini_main.b2c_ali_my_order.phone</code>. 联系电话
     */
    public final TableField<B2cAliMyOrderRecord, String> PHONE = createField("phone", org.jooq.impl.SQLDataType.VARCHAR(191).defaultValue(org.jooq.impl.DSL.inline("1", org.jooq.impl.SQLDataType.VARCHAR)), this, "联系电话");

    /**
     * The column <code>mini_main.b2c_ali_my_order.order_item_num</code>. 门店数量	
     */
    public final TableField<B2cAliMyOrderRecord, UInteger> ORDER_ITEM_NUM = createField("order_item_num", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGERUNSIGNED)), this, "门店数量	");

    /**
     * The column <code>mini_main.b2c_ali_my_order.total_price</code>. 总价格	
     */
    public final TableField<B2cAliMyOrderRecord, BigDecimal> TOTAL_PRICE = createField("total_price", org.jooq.impl.SQLDataType.DECIMAL(10, 2).defaultValue(org.jooq.impl.DSL.inline("0.00", org.jooq.impl.SQLDataType.DECIMAL)), this, "总价格	");

    /**
     * The column <code>mini_main.b2c_ali_my_order.create_time</code>.
     */
    public final TableField<B2cAliMyOrderRecord, Timestamp> CREATE_TIME = createField("create_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * The column <code>mini_main.b2c_ali_my_order.order_ticket</code>. 订单授权码，用于事务创建接口中的入参
     */
    public final TableField<B2cAliMyOrderRecord, String> ORDER_TICKET = createField("order_ticket", org.jooq.impl.SQLDataType.VARCHAR(191), this, "订单授权码，用于事务创建接口中的入参");

    /**
     * The column <code>mini_main.b2c_ali_my_order.service_code</code>. 服务码，用于商户和ISV匹配订单
     */
    public final TableField<B2cAliMyOrderRecord, String> SERVICE_CODE = createField("service_code", org.jooq.impl.SQLDataType.VARCHAR(191), this, "服务码，用于商户和ISV匹配订单");

    /**
     * The column <code>mini_main.b2c_ali_my_order.link_shop_id</code>. 关联店铺Id
     */
    public final TableField<B2cAliMyOrderRecord, Integer> LINK_SHOP_ID = createField("link_shop_id", org.jooq.impl.SQLDataType.INTEGER, this, "关联店铺Id");

    /**
     * Create a <code>mini_main.b2c_ali_my_order</code> table reference
     */
    public B2cAliMyOrder() {
        this(DSL.name("b2c_ali_my_order"), null);
    }

    /**
     * Create an aliased <code>mini_main.b2c_ali_my_order</code> table reference
     */
    public B2cAliMyOrder(String alias) {
        this(DSL.name(alias), B2C_ALI_MY_ORDER);
    }

    /**
     * Create an aliased <code>mini_main.b2c_ali_my_order</code> table reference
     */
    public B2cAliMyOrder(Name alias) {
        this(alias, B2C_ALI_MY_ORDER);
    }

    private B2cAliMyOrder(Name alias, Table<B2cAliMyOrderRecord> aliased) {
        this(alias, aliased, null);
    }

    private B2cAliMyOrder(Name alias, Table<B2cAliMyOrderRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> B2cAliMyOrder(Table<O> child, ForeignKey<O, B2cAliMyOrderRecord> key) {
        super(child, key, B2C_ALI_MY_ORDER);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MiniMain.MINI_MAIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.B2C_ALI_MY_ORDER_COMMODITY_ORDER_ID, Indexes.B2C_ALI_MY_ORDER_LINK_SHOP_ID, Indexes.B2C_ALI_MY_ORDER_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<B2cAliMyOrderRecord, UInteger> getIdentity() {
        return Keys.IDENTITY_B2C_ALI_MY_ORDER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<B2cAliMyOrderRecord> getPrimaryKey() {
        return Keys.KEY_B2C_ALI_MY_ORDER_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<B2cAliMyOrderRecord>> getKeys() {
        return Arrays.<UniqueKey<B2cAliMyOrderRecord>>asList(Keys.KEY_B2C_ALI_MY_ORDER_PRIMARY, Keys.KEY_B2C_ALI_MY_ORDER_COMMODITY_ORDER_ID, Keys.KEY_B2C_ALI_MY_ORDER_LINK_SHOP_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cAliMyOrder as(String alias) {
        return new B2cAliMyOrder(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cAliMyOrder as(Name alias) {
        return new B2cAliMyOrder(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cAliMyOrder rename(String name) {
        return new B2cAliMyOrder(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cAliMyOrder rename(Name name) {
        return new B2cAliMyOrder(name, null);
    }
}
