/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.main.tables;


import com.vpu.mp.db.main.Indexes;
import com.vpu.mp.db.main.Keys;
import com.vpu.mp.db.main.MiniMain;
import com.vpu.mp.db.main.tables.records.B2cDictCountryRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cDictCountry extends TableImpl<B2cDictCountryRecord> {

    private static final long serialVersionUID = -296463974;

    /**
     * The reference instance of <code>mini_main.b2c_dict_country</code>
     */
    public static final B2cDictCountry B2C_DICT_COUNTRY = new B2cDictCountry();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<B2cDictCountryRecord> getRecordType() {
        return B2cDictCountryRecord.class;
    }

    /**
     * The column <code>mini_main.b2c_dict_country.country_id</code>.
     */
    public final TableField<B2cDictCountryRecord, Integer> COUNTRY_ID = createField("country_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>mini_main.b2c_dict_country.name</code>.
     */
    public final TableField<B2cDictCountryRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(60).nullable(false), this, "");

    /**
     * The column <code>mini_main.b2c_dict_country.short_name</code>.
     */
    public final TableField<B2cDictCountryRecord, String> SHORT_NAME = createField("short_name", org.jooq.impl.SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>mini_main.b2c_dict_country.en_name</code>.
     */
    public final TableField<B2cDictCountryRecord, String> EN_NAME = createField("en_name", org.jooq.impl.SQLDataType.VARCHAR(60).nullable(false).defaultValue(org.jooq.impl.DSL.inline("", org.jooq.impl.SQLDataType.VARCHAR)), this, "");

    /**
     * The column <code>mini_main.b2c_dict_country.created</code>.
     */
    public final TableField<B2cDictCountryRecord, Timestamp> CREATED = createField("created", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "");

    /**
     * Create a <code>mini_main.b2c_dict_country</code> table reference
     */
    public B2cDictCountry() {
        this(DSL.name("b2c_dict_country"), null);
    }

    /**
     * Create an aliased <code>mini_main.b2c_dict_country</code> table reference
     */
    public B2cDictCountry(String alias) {
        this(DSL.name(alias), B2C_DICT_COUNTRY);
    }

    /**
     * Create an aliased <code>mini_main.b2c_dict_country</code> table reference
     */
    public B2cDictCountry(Name alias) {
        this(alias, B2C_DICT_COUNTRY);
    }

    private B2cDictCountry(Name alias, Table<B2cDictCountryRecord> aliased) {
        this(alias, aliased, null);
    }

    private B2cDictCountry(Name alias, Table<B2cDictCountryRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> B2cDictCountry(Table<O> child, ForeignKey<O, B2cDictCountryRecord> key) {
        super(child, key, B2C_DICT_COUNTRY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MiniMain.MINI_MAIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.B2C_DICT_COUNTRY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<B2cDictCountryRecord> getPrimaryKey() {
        return Keys.KEY_B2C_DICT_COUNTRY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<B2cDictCountryRecord>> getKeys() {
        return Arrays.<UniqueKey<B2cDictCountryRecord>>asList(Keys.KEY_B2C_DICT_COUNTRY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cDictCountry as(String alias) {
        return new B2cDictCountry(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cDictCountry as(Name alias) {
        return new B2cDictCountry(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cDictCountry rename(String name) {
        return new B2cDictCountry(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cDictCountry rename(Name name) {
        return new B2cDictCountry(name, null);
    }
}
