/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.main.tables;


import com.vpu.mp.db.main.Indexes;
import com.vpu.mp.db.main.MiniMain;
import com.vpu.mp.db.main.tables.records.B2cMpVisitPageRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cMpVisitPage extends TableImpl<B2cMpVisitPageRecord> {

    private static final long serialVersionUID = 126101010;

    /**
     * The reference instance of <code>mini_main.b2c_mp_visit_page</code>
     */
    public static final B2cMpVisitPage B2C_MP_VISIT_PAGE = new B2cMpVisitPage();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<B2cMpVisitPageRecord> getRecordType() {
        return B2cMpVisitPageRecord.class;
    }

    /**
     * The column <code>mini_main.b2c_mp_visit_page.ref_date</code>. 时间，如："20170313"
     */
    public final TableField<B2cMpVisitPageRecord, String> REF_DATE = createField("ref_date", org.jooq.impl.SQLDataType.CHAR(8).nullable(false), this, "时间，如：\"20170313\"");

    /**
     * The column <code>mini_main.b2c_mp_visit_page.page_path</code>.
     */
    public final TableField<B2cMpVisitPageRecord, String> PAGE_PATH = createField("page_path", org.jooq.impl.SQLDataType.VARCHAR(200).nullable(false), this, "");

    /**
     * The column <code>mini_main.b2c_mp_visit_page.page_visit_pv</code>. 访问次数
     */
    public final TableField<B2cMpVisitPageRecord, Integer> PAGE_VISIT_PV = createField("page_visit_pv", org.jooq.impl.SQLDataType.INTEGER, this, "访问次数");

    /**
     * The column <code>mini_main.b2c_mp_visit_page.page_visit_uv</code>. 访问人数
     */
    public final TableField<B2cMpVisitPageRecord, Integer> PAGE_VISIT_UV = createField("page_visit_uv", org.jooq.impl.SQLDataType.INTEGER, this, "访问人数");

    /**
     * The column <code>mini_main.b2c_mp_visit_page.page_staytime_pv</code>. 人均停留时长 (浮点型，单位：秒)
     */
    public final TableField<B2cMpVisitPageRecord, Double> PAGE_STAYTIME_PV = createField("page_staytime_pv", org.jooq.impl.SQLDataType.FLOAT, this, "人均停留时长 (浮点型，单位：秒)");

    /**
     * The column <code>mini_main.b2c_mp_visit_page.entrypage_pv</code>. 进入页次数
     */
    public final TableField<B2cMpVisitPageRecord, Integer> ENTRYPAGE_PV = createField("entrypage_pv", org.jooq.impl.SQLDataType.INTEGER, this, "进入页次数");

    /**
     * The column <code>mini_main.b2c_mp_visit_page.exitpage_pv</code>. 退出页次数
     */
    public final TableField<B2cMpVisitPageRecord, Integer> EXITPAGE_PV = createField("exitpage_pv", org.jooq.impl.SQLDataType.INTEGER, this, "退出页次数");

    /**
     * The column <code>mini_main.b2c_mp_visit_page.page_share_pv</code>. 转发次数
     */
    public final TableField<B2cMpVisitPageRecord, Integer> PAGE_SHARE_PV = createField("page_share_pv", org.jooq.impl.SQLDataType.INTEGER, this, "转发次数");

    /**
     * The column <code>mini_main.b2c_mp_visit_page.page_share_uv</code>. 转发人数
     */
    public final TableField<B2cMpVisitPageRecord, Integer> PAGE_SHARE_UV = createField("page_share_uv", org.jooq.impl.SQLDataType.INTEGER, this, "转发人数");

    /**
     * The column <code>mini_main.b2c_mp_visit_page.add_time</code>. 添加时间
     */
    public final TableField<B2cMpVisitPageRecord, Timestamp> ADD_TIME = createField("add_time", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaultValue(org.jooq.impl.DSL.field("CURRENT_TIMESTAMP", org.jooq.impl.SQLDataType.TIMESTAMP)), this, "添加时间");

    /**
     * Create a <code>mini_main.b2c_mp_visit_page</code> table reference
     */
    public B2cMpVisitPage() {
        this(DSL.name("b2c_mp_visit_page"), null);
    }

    /**
     * Create an aliased <code>mini_main.b2c_mp_visit_page</code> table reference
     */
    public B2cMpVisitPage(String alias) {
        this(DSL.name(alias), B2C_MP_VISIT_PAGE);
    }

    /**
     * Create an aliased <code>mini_main.b2c_mp_visit_page</code> table reference
     */
    public B2cMpVisitPage(Name alias) {
        this(alias, B2C_MP_VISIT_PAGE);
    }

    private B2cMpVisitPage(Name alias, Table<B2cMpVisitPageRecord> aliased) {
        this(alias, aliased, null);
    }

    private B2cMpVisitPage(Name alias, Table<B2cMpVisitPageRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> B2cMpVisitPage(Table<O> child, ForeignKey<O, B2cMpVisitPageRecord> key) {
        super(child, key, B2C_MP_VISIT_PAGE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MiniMain.MINI_MAIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.B2C_MP_VISIT_PAGE_PAGE_PATH, Indexes.B2C_MP_VISIT_PAGE_PAGE_VISIT_PV, Indexes.B2C_MP_VISIT_PAGE_REF_DATE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpVisitPage as(String alias) {
        return new B2cMpVisitPage(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpVisitPage as(Name alias) {
        return new B2cMpVisitPage(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cMpVisitPage rename(String name) {
        return new B2cMpVisitPage(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cMpVisitPage rename(Name name) {
        return new B2cMpVisitPage(name, null);
    }
}
