/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.main.tables;


import com.vpu.mp.db.main.Indexes;
import com.vpu.mp.db.main.Keys;
import com.vpu.mp.db.main.MiniMain;
import com.vpu.mp.db.main.tables.records.B2cMpJumpVersionRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cMpJumpVersion extends TableImpl<B2cMpJumpVersionRecord> {

    private static final long serialVersionUID = -698327154;

    /**
     * The reference instance of <code>mini_main.b2c_mp_jump_version</code>
     */
    public static final B2cMpJumpVersion B2C_MP_JUMP_VERSION = new B2cMpJumpVersion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<B2cMpJumpVersionRecord> getRecordType() {
        return B2cMpJumpVersionRecord.class;
    }

    /**
     * The column <code>mini_main.b2c_mp_jump_version.id</code>.
     */
    public final TableField<B2cMpJumpVersionRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>mini_main.b2c_mp_jump_version.shop_id</code>.
     */
    public final TableField<B2cMpJumpVersionRecord, String> SHOP_ID = createField("shop_id", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>mini_main.b2c_mp_jump_version.flag</code>. 0:申请中，1:已提交
     */
    public final TableField<B2cMpJumpVersionRecord, Byte> FLAG = createField("flag", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.TINYINT)), this, "0:申请中，1:已提交");

    /**
     * The column <code>mini_main.b2c_mp_jump_version.add_time</code>.
     */
    public final TableField<B2cMpJumpVersionRecord, Timestamp> ADD_TIME = createField("add_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>mini_main.b2c_mp_jump_version.update_time</code>.
     */
    public final TableField<B2cMpJumpVersionRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>mini_main.b2c_mp_jump_version</code> table reference
     */
    public B2cMpJumpVersion() {
        this(DSL.name("b2c_mp_jump_version"), null);
    }

    /**
     * Create an aliased <code>mini_main.b2c_mp_jump_version</code> table reference
     */
    public B2cMpJumpVersion(String alias) {
        this(DSL.name(alias), B2C_MP_JUMP_VERSION);
    }

    /**
     * Create an aliased <code>mini_main.b2c_mp_jump_version</code> table reference
     */
    public B2cMpJumpVersion(Name alias) {
        this(alias, B2C_MP_JUMP_VERSION);
    }

    private B2cMpJumpVersion(Name alias, Table<B2cMpJumpVersionRecord> aliased) {
        this(alias, aliased, null);
    }

    private B2cMpJumpVersion(Name alias, Table<B2cMpJumpVersionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> B2cMpJumpVersion(Table<O> child, ForeignKey<O, B2cMpJumpVersionRecord> key) {
        super(child, key, B2C_MP_JUMP_VERSION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MiniMain.MINI_MAIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.B2C_MP_JUMP_VERSION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<B2cMpJumpVersionRecord, Integer> getIdentity() {
        return Keys.IDENTITY_B2C_MP_JUMP_VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<B2cMpJumpVersionRecord> getPrimaryKey() {
        return Keys.KEY_B2C_MP_JUMP_VERSION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<B2cMpJumpVersionRecord>> getKeys() {
        return Arrays.<UniqueKey<B2cMpJumpVersionRecord>>asList(Keys.KEY_B2C_MP_JUMP_VERSION_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpJumpVersion as(String alias) {
        return new B2cMpJumpVersion(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cMpJumpVersion as(Name alias) {
        return new B2cMpJumpVersion(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cMpJumpVersion rename(String name) {
        return new B2cMpJumpVersion(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cMpJumpVersion rename(Name name) {
        return new B2cMpJumpVersion(name, null);
    }
}
