/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.main.tables;


import com.vpu.mp.db.main.Indexes;
import com.vpu.mp.db.main.Keys;
import com.vpu.mp.db.main.MiniMain;
import com.vpu.mp.db.main.tables.records.B2cShopChildRoleRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class B2cShopChildRole extends TableImpl<B2cShopChildRoleRecord> {

    private static final long serialVersionUID = -1347789405;

    /**
     * The reference instance of <code>mini_main.b2c_shop_child_role</code>
     */
    public static final B2cShopChildRole B2C_SHOP_CHILD_ROLE = new B2cShopChildRole();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<B2cShopChildRoleRecord> getRecordType() {
        return B2cShopChildRoleRecord.class;
    }

    /**
     * The column <code>mini_main.b2c_shop_child_role.rec_id</code>.
     */
    public final TableField<B2cShopChildRoleRecord, Integer> REC_ID = createField("rec_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>mini_main.b2c_shop_child_role.sys_id</code>. 主账户ID
     */
    public final TableField<B2cShopChildRoleRecord, Integer> SYS_ID = createField("sys_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "主账户ID");

    /**
     * The column <code>mini_main.b2c_shop_child_role.account_id</code>. 子账户ID
     */
    public final TableField<B2cShopChildRoleRecord, Integer> ACCOUNT_ID = createField("account_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "子账户ID");

    /**
     * The column <code>mini_main.b2c_shop_child_role.shop_id</code>. 店铺ID
     */
    public final TableField<B2cShopChildRoleRecord, Integer> SHOP_ID = createField("shop_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "店铺ID");

    /**
     * The column <code>mini_main.b2c_shop_child_role.role_id</code>. 角色ID
     */
    public final TableField<B2cShopChildRoleRecord, Integer> ROLE_ID = createField("role_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "角色ID");

    /**
     * Create a <code>mini_main.b2c_shop_child_role</code> table reference
     */
    public B2cShopChildRole() {
        this(DSL.name("b2c_shop_child_role"), null);
    }

    /**
     * Create an aliased <code>mini_main.b2c_shop_child_role</code> table reference
     */
    public B2cShopChildRole(String alias) {
        this(DSL.name(alias), B2C_SHOP_CHILD_ROLE);
    }

    /**
     * Create an aliased <code>mini_main.b2c_shop_child_role</code> table reference
     */
    public B2cShopChildRole(Name alias) {
        this(alias, B2C_SHOP_CHILD_ROLE);
    }

    private B2cShopChildRole(Name alias, Table<B2cShopChildRoleRecord> aliased) {
        this(alias, aliased, null);
    }

    private B2cShopChildRole(Name alias, Table<B2cShopChildRoleRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> B2cShopChildRole(Table<O> child, ForeignKey<O, B2cShopChildRoleRecord> key) {
        super(child, key, B2C_SHOP_CHILD_ROLE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return MiniMain.MINI_MAIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.B2C_SHOP_CHILD_ROLE_ACCOUNT_ID, Indexes.B2C_SHOP_CHILD_ROLE_PRIMARY, Indexes.B2C_SHOP_CHILD_ROLE_SYS_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<B2cShopChildRoleRecord, Integer> getIdentity() {
        return Keys.IDENTITY_B2C_SHOP_CHILD_ROLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<B2cShopChildRoleRecord> getPrimaryKey() {
        return Keys.KEY_B2C_SHOP_CHILD_ROLE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<B2cShopChildRoleRecord>> getKeys() {
        return Arrays.<UniqueKey<B2cShopChildRoleRecord>>asList(Keys.KEY_B2C_SHOP_CHILD_ROLE_PRIMARY, Keys.KEY_B2C_SHOP_CHILD_ROLE_ACCOUNT_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cShopChildRole as(String alias) {
        return new B2cShopChildRole(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public B2cShopChildRole as(Name alias) {
        return new B2cShopChildRole(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cShopChildRole rename(String name) {
        return new B2cShopChildRole(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public B2cShopChildRole rename(Name name) {
        return new B2cShopChildRole(name, null);
    }
}
