/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables.pojos;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LotteryPrize implements Serializable {

    private static final long serialVersionUID = -551099239;

    private Integer   id;
    private Integer   lotteryId;
    private Integer   chanceNumerator;
    private Integer   chanceDenominator;
    private Byte      lotteryGrade;
    private String    lotteryDetail;
    private String    iconImgsImage;
    private String    iconImgs;
    private Byte      lotteryType;
    private Integer   lotteryNumber;
    private Integer   awardTimes;
    private Integer   integralScore;
    private Byte      couponId;
    private Byte      prdId;
    private Byte      prdKeepDays;
    private Byte      delFlag;
    private Timestamp createTime;
    private Timestamp updateTime;

    public LotteryPrize() {}

    public LotteryPrize(LotteryPrize value) {
        this.id = value.id;
        this.lotteryId = value.lotteryId;
        this.chanceNumerator = value.chanceNumerator;
        this.chanceDenominator = value.chanceDenominator;
        this.lotteryGrade = value.lotteryGrade;
        this.lotteryDetail = value.lotteryDetail;
        this.iconImgsImage = value.iconImgsImage;
        this.iconImgs = value.iconImgs;
        this.lotteryType = value.lotteryType;
        this.lotteryNumber = value.lotteryNumber;
        this.awardTimes = value.awardTimes;
        this.integralScore = value.integralScore;
        this.couponId = value.couponId;
        this.prdId = value.prdId;
        this.prdKeepDays = value.prdKeepDays;
        this.delFlag = value.delFlag;
        this.createTime = value.createTime;
        this.updateTime = value.updateTime;
    }

    public LotteryPrize(
        Integer   id,
        Integer   lotteryId,
        Integer   chanceNumerator,
        Integer   chanceDenominator,
        Byte      lotteryGrade,
        String    lotteryDetail,
        String    iconImgsImage,
        String    iconImgs,
        Byte      lotteryType,
        Integer   lotteryNumber,
        Integer   awardTimes,
        Integer   integralScore,
        Byte      couponId,
        Byte      prdId,
        Byte      prdKeepDays,
        Byte      delFlag,
        Timestamp createTime,
        Timestamp updateTime
    ) {
        this.id = id;
        this.lotteryId = lotteryId;
        this.chanceNumerator = chanceNumerator;
        this.chanceDenominator = chanceDenominator;
        this.lotteryGrade = lotteryGrade;
        this.lotteryDetail = lotteryDetail;
        this.iconImgsImage = iconImgsImage;
        this.iconImgs = iconImgs;
        this.lotteryType = lotteryType;
        this.lotteryNumber = lotteryNumber;
        this.awardTimes = awardTimes;
        this.integralScore = integralScore;
        this.couponId = couponId;
        this.prdId = prdId;
        this.prdKeepDays = prdKeepDays;
        this.delFlag = delFlag;
        this.createTime = createTime;
        this.updateTime = updateTime;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getLotteryId() {
        return this.lotteryId;
    }

    public void setLotteryId(Integer lotteryId) {
        this.lotteryId = lotteryId;
    }

    public Integer getChanceNumerator() {
        return this.chanceNumerator;
    }

    public void setChanceNumerator(Integer chanceNumerator) {
        this.chanceNumerator = chanceNumerator;
    }

    public Integer getChanceDenominator() {
        return this.chanceDenominator;
    }

    public void setChanceDenominator(Integer chanceDenominator) {
        this.chanceDenominator = chanceDenominator;
    }

    public Byte getLotteryGrade() {
        return this.lotteryGrade;
    }

    public void setLotteryGrade(Byte lotteryGrade) {
        this.lotteryGrade = lotteryGrade;
    }

    public String getLotteryDetail() {
        return this.lotteryDetail;
    }

    public void setLotteryDetail(String lotteryDetail) {
        this.lotteryDetail = lotteryDetail;
    }

    public String getIconImgsImage() {
        return this.iconImgsImage;
    }

    public void setIconImgsImage(String iconImgsImage) {
        this.iconImgsImage = iconImgsImage;
    }

    public String getIconImgs() {
        return this.iconImgs;
    }

    public void setIconImgs(String iconImgs) {
        this.iconImgs = iconImgs;
    }

    public Byte getLotteryType() {
        return this.lotteryType;
    }

    public void setLotteryType(Byte lotteryType) {
        this.lotteryType = lotteryType;
    }

    public Integer getLotteryNumber() {
        return this.lotteryNumber;
    }

    public void setLotteryNumber(Integer lotteryNumber) {
        this.lotteryNumber = lotteryNumber;
    }

    public Integer getAwardTimes() {
        return this.awardTimes;
    }

    public void setAwardTimes(Integer awardTimes) {
        this.awardTimes = awardTimes;
    }

    public Integer getIntegralScore() {
        return this.integralScore;
    }

    public void setIntegralScore(Integer integralScore) {
        this.integralScore = integralScore;
    }

    public Byte getCouponId() {
        return this.couponId;
    }

    public void setCouponId(Byte couponId) {
        this.couponId = couponId;
    }

    public Byte getPrdId() {
        return this.prdId;
    }

    public void setPrdId(Byte prdId) {
        this.prdId = prdId;
    }

    public Byte getPrdKeepDays() {
        return this.prdKeepDays;
    }

    public void setPrdKeepDays(Byte prdKeepDays) {
        this.prdKeepDays = prdKeepDays;
    }

    public Byte getDelFlag() {
        return this.delFlag;
    }

    public void setDelFlag(Byte delFlag) {
        this.delFlag = delFlag;
    }

    public Timestamp getCreateTime() {
        return this.createTime;
    }

    public void setCreateTime(Timestamp createTime) {
        this.createTime = createTime;
    }

    public Timestamp getUpdateTime() {
        return this.updateTime;
    }

    public void setUpdateTime(Timestamp updateTime) {
        this.updateTime = updateTime;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LotteryPrize (");

        sb.append(id);
        sb.append(", ").append(lotteryId);
        sb.append(", ").append(chanceNumerator);
        sb.append(", ").append(chanceDenominator);
        sb.append(", ").append(lotteryGrade);
        sb.append(", ").append(lotteryDetail);
        sb.append(", ").append(iconImgsImage);
        sb.append(", ").append(iconImgs);
        sb.append(", ").append(lotteryType);
        sb.append(", ").append(lotteryNumber);
        sb.append(", ").append(awardTimes);
        sb.append(", ").append(integralScore);
        sb.append(", ").append(couponId);
        sb.append(", ").append(prdId);
        sb.append(", ").append(prdKeepDays);
        sb.append(", ").append(delFlag);
        sb.append(", ").append(createTime);
        sb.append(", ").append(updateTime);

        sb.append(")");
        return sb.toString();
    }
}
