/*
 * This file is generated by jOOQ.
 */
package com.vpu.mp.db.shop.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class LotteryPrize implements Serializable {

    private static final long serialVersionUID = 1175262091;

    private Integer id;
    private Integer lotteryId;
    private Byte    lotteryGrade;
    private Byte    chance;
    private Byte    presentType;
    private Integer presentNumber;
    private Integer integralScore;
    private Byte    couponId;
    private Byte    prdId;
    private Byte    prdKeepDays;
    private String  presentDetail;
    private String  iconImgsImage;
    private String  iconImgs;

    public LotteryPrize() {}

    public LotteryPrize(LotteryPrize value) {
        this.id = value.id;
        this.lotteryId = value.lotteryId;
        this.lotteryGrade = value.lotteryGrade;
        this.chance = value.chance;
        this.presentType = value.presentType;
        this.presentNumber = value.presentNumber;
        this.integralScore = value.integralScore;
        this.couponId = value.couponId;
        this.prdId = value.prdId;
        this.prdKeepDays = value.prdKeepDays;
        this.presentDetail = value.presentDetail;
        this.iconImgsImage = value.iconImgsImage;
        this.iconImgs = value.iconImgs;
    }

    public LotteryPrize(
        Integer id,
        Integer lotteryId,
        Byte    lotteryGrade,
        Byte    chance,
        Byte    presentType,
        Integer presentNumber,
        Integer integralScore,
        Byte    couponId,
        Byte    prdId,
        Byte    prdKeepDays,
        String  presentDetail,
        String  iconImgsImage,
        String  iconImgs
    ) {
        this.id = id;
        this.lotteryId = lotteryId;
        this.lotteryGrade = lotteryGrade;
        this.chance = chance;
        this.presentType = presentType;
        this.presentNumber = presentNumber;
        this.integralScore = integralScore;
        this.couponId = couponId;
        this.prdId = prdId;
        this.prdKeepDays = prdKeepDays;
        this.presentDetail = presentDetail;
        this.iconImgsImage = iconImgsImage;
        this.iconImgs = iconImgs;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getLotteryId() {
        return this.lotteryId;
    }

    public void setLotteryId(Integer lotteryId) {
        this.lotteryId = lotteryId;
    }

    public Byte getLotteryGrade() {
        return this.lotteryGrade;
    }

    public void setLotteryGrade(Byte lotteryGrade) {
        this.lotteryGrade = lotteryGrade;
    }

    public Byte getChance() {
        return this.chance;
    }

    public void setChance(Byte chance) {
        this.chance = chance;
    }

    public Byte getPresentType() {
        return this.presentType;
    }

    public void setPresentType(Byte presentType) {
        this.presentType = presentType;
    }

    public Integer getPresentNumber() {
        return this.presentNumber;
    }

    public void setPresentNumber(Integer presentNumber) {
        this.presentNumber = presentNumber;
    }

    public Integer getIntegralScore() {
        return this.integralScore;
    }

    public void setIntegralScore(Integer integralScore) {
        this.integralScore = integralScore;
    }

    public Byte getCouponId() {
        return this.couponId;
    }

    public void setCouponId(Byte couponId) {
        this.couponId = couponId;
    }

    public Byte getPrdId() {
        return this.prdId;
    }

    public void setPrdId(Byte prdId) {
        this.prdId = prdId;
    }

    public Byte getPrdKeepDays() {
        return this.prdKeepDays;
    }

    public void setPrdKeepDays(Byte prdKeepDays) {
        this.prdKeepDays = prdKeepDays;
    }

    public String getPresentDetail() {
        return this.presentDetail;
    }

    public void setPresentDetail(String presentDetail) {
        this.presentDetail = presentDetail;
    }

    public String getIconImgsImage() {
        return this.iconImgsImage;
    }

    public void setIconImgsImage(String iconImgsImage) {
        this.iconImgsImage = iconImgsImage;
    }

    public String getIconImgs() {
        return this.iconImgs;
    }

    public void setIconImgs(String iconImgs) {
        this.iconImgs = iconImgs;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("LotteryPrize (");

        sb.append(id);
        sb.append(", ").append(lotteryId);
        sb.append(", ").append(lotteryGrade);
        sb.append(", ").append(chance);
        sb.append(", ").append(presentType);
        sb.append(", ").append(presentNumber);
        sb.append(", ").append(integralScore);
        sb.append(", ").append(couponId);
        sb.append(", ").append(prdId);
        sb.append(", ").append(prdKeepDays);
        sb.append(", ").append(presentDetail);
        sb.append(", ").append(iconImgsImage);
        sb.append(", ").append(iconImgs);

        sb.append(")");
        return sb.toString();
    }
}
